// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ListFilesParamsScope.
const (
	Accessible ListFilesParamsScope = "accessible"
	Course     ListFilesParamsScope = "course"
	Owned      ListFilesParamsScope = "owned"
	StudyGuide ListFilesParamsScope = "study_guide"
)

// Valid indicates whether the value is a known member of the ListFilesParamsScope enum.
func (e ListFilesParamsScope) Valid() bool {
	switch e {
	case Accessible:
		return true
	case Course:
		return true
	case Owned:
		return true
	case StudyGuide:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsStatus.
const (
	Complete ListFilesParamsStatus = "complete"
	Failed   ListFilesParamsStatus = "failed"
	Pending  ListFilesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListFilesParamsStatus enum.
func (e ListFilesParamsStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	case Failed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsMimeType.
const (
	Applicationpdf ListFilesParamsMimeType = "application/pdf"
	Imagejpeg      ListFilesParamsMimeType = "image/jpeg"
	Imagepng       ListFilesParamsMimeType = "image/png"
	Imagewebp      ListFilesParamsMimeType = "image/webp"
)

// Valid indicates whether the value is a known member of the ListFilesParamsMimeType enum.
func (e ListFilesParamsMimeType) Valid() bool {
	switch e {
	case Applicationpdf:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSortBy.
const (
	CreatedAt ListFilesParamsSortBy = "created_at"
	MimeType  ListFilesParamsSortBy = "mime_type"
	Name      ListFilesParamsSortBy = "name"
	Size      ListFilesParamsSortBy = "size"
	Status    ListFilesParamsSortBy = "status"
	UpdatedAt ListFilesParamsSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSortBy enum.
func (e ListFilesParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case MimeType:
		return true
	case Name:
		return true
	case Size:
		return true
	case Status:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSortDir.
const (
	Asc  ListFilesParamsSortDir = "asc"
	Desc ListFilesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSortDir enum.
func (e ListFilesParamsSortDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// AppError Standardized error response structure matching application error domains
type AppError struct {
	Code    int                `json:"code"`
	Details *map[string]string `json:"details,omitempty"`
	Message string             `json:"message"`
	Status  string             `json:"status"`
}

// FileResponse Complete metadata payload describing an uploaded file
type FileResponse struct {
	CreatedAt    time.Time          `json:"created_at"`
	FavoritedAt  *time.Time         `json:"favorited_at,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	LastViewedAt *time.Time         `json:"last_viewed_at,omitempty"`
	MimeType     string             `json:"mime_type"`
	Name         string             `json:"name"`
	Size         int64              `json:"size"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// ListFilesResponse A paginated collection of files
type ListFilesResponse struct {
	Files      []FileResponse `json:"files"`
	HasMore    bool           `json:"has_more"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// UpdateFileRequest Request body for updating file metadata
type UpdateFileRequest struct {
	Name string `json:"name"`
}

// BadRequest Standardized error response structure matching application error domains
type BadRequest = AppError

// Forbidden Standardized error response structure matching application error domains
type Forbidden = AppError

// InternalServerError Standardized error response structure matching application error domains
type InternalServerError = AppError

// NotFound Standardized error response structure matching application error domains
type NotFound = AppError

// Unauthorized Standardized error response structure matching application error domains
type Unauthorized = AppError

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Scope Filter files by ownership or access level
	Scope *ListFilesParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Status Filter files by processing status
	Status *ListFilesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// MimeType Filter by precise document mime-type classification
	MimeType *ListFilesParamsMimeType `form:"mime_type,omitempty" json:"mime_type,omitempty"`

	// MinSize Minimum file size in bytes
	MinSize *int64 `form:"min_size,omitempty" json:"min_size,omitempty"`

	// MaxSize Maximum file size in bytes
	MaxSize *int64 `form:"max_size,omitempty" json:"max_size,omitempty"`

	// CreatedFrom Filter for files created on or after this UTC timestamp
	CreatedFrom *time.Time `form:"created_from,omitempty" json:"created_from,omitempty"`

	// CreatedTo Filter for files created on or before this UTC timestamp
	CreatedTo *time.Time `form:"created_to,omitempty" json:"created_to,omitempty"`

	// UpdatedFrom Filter for files updated on or after this UTC timestamp
	UpdatedFrom *time.Time `form:"updated_from,omitempty" json:"updated_from,omitempty"`

	// UpdatedTo Filter for files updated on or before this UTC timestamp
	UpdatedTo *time.Time `form:"updated_to,omitempty" json:"updated_to,omitempty"`

	// Q Search term to partially match against file names
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// SortBy Database column to sort the results by
	SortBy *ListFilesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sorting direction (ascending or descending)
	SortDir *ListFilesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// PageLimit Maximum number of files to return per page
	PageLimit *int `form:"page_limit,omitempty" json:"page_limit,omitempty"`

	// Cursor Opaque pagination cursor token obtained from the previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListFilesParamsScope defines parameters for ListFiles.
type ListFilesParamsScope string

// ListFilesParamsStatus defines parameters for ListFiles.
type ListFilesParamsStatus string

// ListFilesParamsMimeType defines parameters for ListFiles.
type ListFilesParamsMimeType string

// ListFilesParamsSortBy defines parameters for ListFiles.
type ListFilesParamsSortBy string

// ListFilesParamsSortDir defines parameters for ListFiles.
type ListFilesParamsSortDir string

// UpdateFileJSONRequestBody defines body for UpdateFile for application/json ContentType.
type UpdateFileJSONRequestBody = UpdateFileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Delete a file by ID
	// (DELETE /files/{file_id})
	DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Get a file by ID
	// (GET /files/{file_id})
	GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Update file metadata (rename)
	// (PATCH /files/{file_id})
	UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// List files for the current user
	// (GET /me/files)
	ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Delete a file by ID
// (DELETE /files/{file_id})
func (_ Unimplemented) DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a file by ID
// (GET /files/{file_id})
func (_ Unimplemented) GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update file metadata (rename)
// (PATCH /files/{file_id})
func (_ Unimplemented) UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List files for the current user
// (GET /me/files)
func (_ Unimplemented) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DeleteFile operation middleware
func (siw *ServerInterfaceWrapper) DeleteFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFile operation middleware
func (siw *ServerInterfaceWrapper) GetFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFile operation middleware
func (siw *ServerInterfaceWrapper) UpdateFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFiles operation middleware
func (siw *ServerInterfaceWrapper) ListFiles(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", r.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "mime_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mime_type", r.URL.Query(), &params.MimeType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mime_type", Err: err})
		return
	}

	// ------------- Optional query parameter "min_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_size", r.URL.Query(), &params.MinSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_size", Err: err})
		return
	}

	// ------------- Optional query parameter "max_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_size", r.URL.Query(), &params.MaxSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_size", Err: err})
		return
	}

	// ------------- Optional query parameter "created_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_from", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_from", Err: err})
		return
	}

	// ------------- Optional query parameter "created_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_to", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_to", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_from", r.URL.Query(), &params.UpdatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_from", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_to", r.URL.Query(), &params.UpdatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_to", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_limit", r.URL.Query(), &params.PageLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/files/{file_id}", wrapper.DeleteFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{file_id}", wrapper.GetFile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/files/{file_id}", wrapper.UpdateFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/files", wrapper.ListFiles)
	})

	return r
}

type BadRequestJSONResponse AppError

type ForbiddenJSONResponse AppError

type InternalServerErrorJSONResponse AppError

type NotFoundJSONResponse AppError

type UnauthorizedJSONResponse AppError

type DeleteFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
}

type DeleteFileResponseObject interface {
	VisitDeleteFileResponse(w http.ResponseWriter) error
}

type DeleteFile204Response struct {
}

func (response DeleteFile204Response) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteFile401JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteFile404JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteFile500JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
}

type GetFileResponseObject interface {
	VisitGetFileResponse(w http.ResponseWriter) error
}

type GetFile200JSONResponse FileResponse

func (response GetFile200JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFile400JSONResponse struct{ BadRequestJSONResponse }

func (response GetFile400JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetFile401JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetFile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetFile403JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetFile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetFile404JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetFile500JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
	Body   *UpdateFileJSONRequestBody
}

type UpdateFileResponseObject interface {
	VisitUpdateFileResponse(w http.ResponseWriter) error
}

type UpdateFile200JSONResponse FileResponse

func (response UpdateFile200JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateFile400JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateFile401JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateFile404JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateFile500JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListFilesRequestObject struct {
	Params ListFilesParams
}

type ListFilesResponseObject interface {
	VisitListFilesResponse(w http.ResponseWriter) error
}

type ListFiles200JSONResponse ListFilesResponse

func (response ListFiles200JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles400JSONResponse struct{ BadRequestJSONResponse }

func (response ListFiles400JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListFiles401JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListFiles500JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Delete a file by ID
	// (DELETE /files/{file_id})
	DeleteFile(ctx context.Context, request DeleteFileRequestObject) (DeleteFileResponseObject, error)
	// Get a file by ID
	// (GET /files/{file_id})
	GetFile(ctx context.Context, request GetFileRequestObject) (GetFileResponseObject, error)
	// Update file metadata (rename)
	// (PATCH /files/{file_id})
	UpdateFile(ctx context.Context, request UpdateFileRequestObject) (UpdateFileResponseObject, error)
	// List files for the current user
	// (GET /me/files)
	ListFiles(ctx context.Context, request ListFilesRequestObject) (ListFilesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DeleteFile operation middleware
func (sh *strictHandler) DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request DeleteFileRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFile(ctx, request.(DeleteFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFileResponseObject); ok {
		if err := validResponse.VisitDeleteFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFile operation middleware
func (sh *strictHandler) GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request GetFileRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFile(ctx, request.(GetFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFileResponseObject); ok {
		if err := validResponse.VisitGetFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFile operation middleware
func (sh *strictHandler) UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request UpdateFileRequestObject

	request.FileId = fileId

	var body UpdateFileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFile(ctx, request.(UpdateFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateFileResponseObject); ok {
		if err := validResponse.VisitUpdateFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFiles operation middleware
func (sh *strictHandler) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	var request ListFilesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFiles(ctx, request.(ListFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFilesResponseObject); ok {
		if err := validResponse.VisitListFilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RZ328bNxL+VwjePbSAGsn5cQ96c5tz4UOvV9Qx7iEwhNFyVmK6/OEh6UQ19L8fhtxd",
	"aaNVZPcc58nicsn5OPPx25nxvayc8c6ijUHO7yVh8M4GzIMfQf2OtwlD5FHlbESbf4L3ja4gamenH4Kz",
	"/CxUazTAv/5OWMu5/Nt0t/W0zIbpuff/JHIkt9vtRCoMFWnP+8g5mxPU2ttO5IWjpVYK7bMY31nbTuSl",
	"jUgWmiukO6Sy5jlAdHZFyIYFlhcn8lcXL1yy6llQ/OqiqLO17UReW0hx7Uj/ic9jfWCQp9tFvGe/bn7/",
	"2aqrCFYBKV5V3CY6KosQKVUxEQoDsVpruxJ70Nu3lTOgbZAT6cl5pKjLHaicQv4bNx7lXGobcYU5Jgoj",
	"6Ca/BEpp3gua3waL20UhkrYrXtM+cMsPWGWSGwwBVjj6cogQ09g+24nke6KJQ/K+QOxf3+15M2LvQjf4",
	"e+uYQy/+5IxvMKIwGEFBBOFh0zhQory3zL6zInl+iErUusFDlxFCRLWAzJLakeFfUkHEH6I2vODgrDXc",
	"OdInVtnUNLBsUM4jJRzZRavB2pS0GjPWQIiLO40f/09zRhtclKcj4bNgjsRV/4kDo9rGf7zeAd3j2FEK",
	"TGTy6pFe/ow22TcZZAtp/0B7dNoL58DqGL1+0SEyxcJxjp0LDytteRdRuabBKt9CV2cyHV7A8nR+L3VE",
	"E04py4DfuwsHRLDh8RrCwjjaD8zSuQYh677FT3FRJQpFYk4Q4DN/dvB7E2MOus7+Kyj7L+vQQe2EWDq1",
	"EbUjkX3ON48t9FfzwFEd3wx8+gXtKq7l/OWbNxxU243PTp0h73GIm5mIVSIdN1fs6DY9QCCk88Q738tl",
	"Hl10PPzXf9/JVruzk/PsjpPrGH1Rf21rl6OhI3tanoc/zmMDQZz/dikn8g4pFL+cvZi9mLEPnUcLXsu5",
	"fPVi9uIVOwLiOkOa5iBM7/nPQqtt8S5LGv9ib2XNv1RyLt/m5xetggGBwYgU5Pz95xF5t0aRrL5NKK6v",
	"L98KQk8Y0OagxDWWwEQnWlN8KDnPqLorNpctJLnv8EKr3TfzhHJtbybDBO3l7PUhf/hEIqSqwhDq1DQb",
	"cZswsVjzZ44R8nvbiXw9Ozt2nXor0+HnmBe9Pr2oT1e2E/lmNju9YCzhyqxLxgBt+mgJKL5ebsTlW959",
	"hfEwsj9jfLKwPmcwZ0+WYA1l8DDJOi9ny/F8QHj2CoG/zptXpxcNkvBvxbSfMR7QzHPieEi0nZo/mYSU",
	"D+xXZl0O5Y9ObZ6McIffte3w28I4t9+Q8Yeq2KYyz3sJvg2lS3SG+YP4jpB59X1+d2pw2mdao6Lap3an",
	"qH6hm4hUsjm+Qe6jRQpr7YUjATkAosE7bDqS3yakzY7loXIlAe3jrrCG1DCpeS9mNdpkOF/pxpVLFErW",
	"mtRmsUo6l0TFmuYU7mYk9TmF3JPL6+1K9NnwKOJucgxy1dZUe6g9WsUQJvuTNegG1WNwZoRY6YBCuSoZ",
	"tFFwBv8DbyCqBkLQdXubjiAfJPw9+A6nNrDC6QePDLUMvN39/ohLz07eu7Ne1Q86wb+11SaZwkguPoS2",
	"YrmJGI4CtYu2SBnRuq6AMmVbOZ8dFlMjIODTI0HApycH0XHOdbxryy3BNREJqHk2rnUQ1+9+ElzYhQjG",
	"H0HY1Wo1OTOO8ov14SPBLbF2hI9HF93XwNbq+V9zXFfXfi3HDcE91nEduidx3BUCVWsRkQwnHB4oauAP",
	"Yu6OCViBtiGWW8H2j92G2wGWk2bfQoQlBOSiPxnLpoOjmJMfwpCayJp7TGEdxUWeHZPYvabETmQHDwc9",
	"jGHPY9c267XwIQp25SjnbkpT28H4DkJVhF3kQqsbff+lMylNRw7FG+wdB/IoP3yQwLbaZpNZIvXdFfY6",
	"YUxkhUcSHlZ4BB1PLRptdBzH9/LNhPWwKN3ZbLane2cP0b3/eOBkuO0Fsf9K30VE9wda4ZYRtOWilZzJ",
	"HPGEd9ql0Pd1j4lMad98iZtfs/I67ICNll+NDnHX83rGFPSJMko+ZkspFjkOUJWIOAVJAdvGftczykni",
	"frfo/Q3HoPyTo6SQiRo5l1PwWm5vtv8LAAD///PPvaKWGgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
