// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CreateFileRequestMimeType.
const (
	CreateFileRequestMimeTypeApplicationepubZip                                                   CreateFileRequestMimeType = "application/epub+zip"
	CreateFileRequestMimeTypeApplicationpdf                                                       CreateFileRequestMimeType = "application/pdf"
	CreateFileRequestMimeTypeApplicationvndOpenxmlformatsOfficedocumentPresentationmlPresentation CreateFileRequestMimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	CreateFileRequestMimeTypeApplicationvndOpenxmlformatsOfficedocumentWordprocessingmlDocument   CreateFileRequestMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	CreateFileRequestMimeTypeImagejpeg                                                            CreateFileRequestMimeType = "image/jpeg"
	CreateFileRequestMimeTypeImagepng                                                             CreateFileRequestMimeType = "image/png"
	CreateFileRequestMimeTypeImagewebp                                                            CreateFileRequestMimeType = "image/webp"
	CreateFileRequestMimeTypeTextplain                                                            CreateFileRequestMimeType = "text/plain"
)

// Valid indicates whether the value is a known member of the CreateFileRequestMimeType enum.
func (e CreateFileRequestMimeType) Valid() bool {
	switch e {
	case CreateFileRequestMimeTypeApplicationepubZip:
		return true
	case CreateFileRequestMimeTypeApplicationpdf:
		return true
	case CreateFileRequestMimeTypeApplicationvndOpenxmlformatsOfficedocumentPresentationmlPresentation:
		return true
	case CreateFileRequestMimeTypeApplicationvndOpenxmlformatsOfficedocumentWordprocessingmlDocument:
		return true
	case CreateFileRequestMimeTypeImagejpeg:
		return true
	case CreateFileRequestMimeTypeImagepng:
		return true
	case CreateFileRequestMimeTypeImagewebp:
		return true
	case CreateFileRequestMimeTypeTextplain:
		return true
	default:
		return false
	}
}

// Defines values for CreateGrantRequestGranteeType.
const (
	CreateGrantRequestGranteeTypeCourse     CreateGrantRequestGranteeType = "course"
	CreateGrantRequestGranteeTypeStudyGuide CreateGrantRequestGranteeType = "study_guide"
	CreateGrantRequestGranteeTypeUser       CreateGrantRequestGranteeType = "user"
)

// Valid indicates whether the value is a known member of the CreateGrantRequestGranteeType enum.
func (e CreateGrantRequestGranteeType) Valid() bool {
	switch e {
	case CreateGrantRequestGranteeTypeCourse:
		return true
	case CreateGrantRequestGranteeTypeStudyGuide:
		return true
	case CreateGrantRequestGranteeTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for CreateGrantRequestPermission.
const (
	CreateGrantRequestPermissionDelete CreateGrantRequestPermission = "delete"
	CreateGrantRequestPermissionShare  CreateGrantRequestPermission = "share"
	CreateGrantRequestPermissionView   CreateGrantRequestPermission = "view"
)

// Valid indicates whether the value is a known member of the CreateGrantRequestPermission enum.
func (e CreateGrantRequestPermission) Valid() bool {
	switch e {
	case CreateGrantRequestPermissionDelete:
		return true
	case CreateGrantRequestPermissionShare:
		return true
	case CreateGrantRequestPermissionView:
		return true
	default:
		return false
	}
}

// Defines values for RevokeGrantRequestGranteeType.
const (
	RevokeGrantRequestGranteeTypeCourse     RevokeGrantRequestGranteeType = "course"
	RevokeGrantRequestGranteeTypeStudyGuide RevokeGrantRequestGranteeType = "study_guide"
	RevokeGrantRequestGranteeTypeUser       RevokeGrantRequestGranteeType = "user"
)

// Valid indicates whether the value is a known member of the RevokeGrantRequestGranteeType enum.
func (e RevokeGrantRequestGranteeType) Valid() bool {
	switch e {
	case RevokeGrantRequestGranteeTypeCourse:
		return true
	case RevokeGrantRequestGranteeTypeStudyGuide:
		return true
	case RevokeGrantRequestGranteeTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for RevokeGrantRequestPermission.
const (
	RevokeGrantRequestPermissionDelete RevokeGrantRequestPermission = "delete"
	RevokeGrantRequestPermissionShare  RevokeGrantRequestPermission = "share"
	RevokeGrantRequestPermissionView   RevokeGrantRequestPermission = "view"
)

// Valid indicates whether the value is a known member of the RevokeGrantRequestPermission enum.
func (e RevokeGrantRequestPermission) Valid() bool {
	switch e {
	case RevokeGrantRequestPermissionDelete:
		return true
	case RevokeGrantRequestPermissionShare:
		return true
	case RevokeGrantRequestPermissionView:
		return true
	default:
		return false
	}
}

// Defines values for ListCoursesParamsSortBy.
const (
	ListCoursesParamsSortByCreatedAt  ListCoursesParamsSortBy = "created_at"
	ListCoursesParamsSortByDepartment ListCoursesParamsSortBy = "department"
	ListCoursesParamsSortByNumber     ListCoursesParamsSortBy = "number"
	ListCoursesParamsSortByTitle      ListCoursesParamsSortBy = "title"
)

// Valid indicates whether the value is a known member of the ListCoursesParamsSortBy enum.
func (e ListCoursesParamsSortBy) Valid() bool {
	switch e {
	case ListCoursesParamsSortByCreatedAt:
		return true
	case ListCoursesParamsSortByDepartment:
		return true
	case ListCoursesParamsSortByNumber:
		return true
	case ListCoursesParamsSortByTitle:
		return true
	default:
		return false
	}
}

// Defines values for ListCoursesParamsSortDir.
const (
	ListCoursesParamsSortDirAsc  ListCoursesParamsSortDir = "asc"
	ListCoursesParamsSortDirDesc ListCoursesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListCoursesParamsSortDir enum.
func (e ListCoursesParamsSortDir) Valid() bool {
	switch e {
	case ListCoursesParamsSortDirAsc:
		return true
	case ListCoursesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsScope.
const (
	Accessible ListFilesParamsScope = "accessible"
	Course     ListFilesParamsScope = "course"
	Owned      ListFilesParamsScope = "owned"
	StudyGuide ListFilesParamsScope = "study_guide"
)

// Valid indicates whether the value is a known member of the ListFilesParamsScope enum.
func (e ListFilesParamsScope) Valid() bool {
	switch e {
	case Accessible:
		return true
	case Course:
		return true
	case Owned:
		return true
	case StudyGuide:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsStatus.
const (
	Complete ListFilesParamsStatus = "complete"
	Failed   ListFilesParamsStatus = "failed"
	Pending  ListFilesParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the ListFilesParamsStatus enum.
func (e ListFilesParamsStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	case Failed:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsMimeType.
const (
	ListFilesParamsMimeTypeApplicationepubZip                                                   ListFilesParamsMimeType = "application/epub+zip"
	ListFilesParamsMimeTypeApplicationpdf                                                       ListFilesParamsMimeType = "application/pdf"
	ListFilesParamsMimeTypeApplicationvndOpenxmlformatsOfficedocumentPresentationmlPresentation ListFilesParamsMimeType = "application/vnd.openxmlformats-officedocument.presentationml.presentation"
	ListFilesParamsMimeTypeApplicationvndOpenxmlformatsOfficedocumentWordprocessingmlDocument   ListFilesParamsMimeType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
	ListFilesParamsMimeTypeImagejpeg                                                            ListFilesParamsMimeType = "image/jpeg"
	ListFilesParamsMimeTypeImagepng                                                             ListFilesParamsMimeType = "image/png"
	ListFilesParamsMimeTypeImagewebp                                                            ListFilesParamsMimeType = "image/webp"
	ListFilesParamsMimeTypeTextplain                                                            ListFilesParamsMimeType = "text/plain"
)

// Valid indicates whether the value is a known member of the ListFilesParamsMimeType enum.
func (e ListFilesParamsMimeType) Valid() bool {
	switch e {
	case ListFilesParamsMimeTypeApplicationepubZip:
		return true
	case ListFilesParamsMimeTypeApplicationpdf:
		return true
	case ListFilesParamsMimeTypeApplicationvndOpenxmlformatsOfficedocumentPresentationmlPresentation:
		return true
	case ListFilesParamsMimeTypeApplicationvndOpenxmlformatsOfficedocumentWordprocessingmlDocument:
		return true
	case ListFilesParamsMimeTypeImagejpeg:
		return true
	case ListFilesParamsMimeTypeImagepng:
		return true
	case ListFilesParamsMimeTypeImagewebp:
		return true
	case ListFilesParamsMimeTypeTextplain:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSortBy.
const (
	ListFilesParamsSortByCreatedAt ListFilesParamsSortBy = "created_at"
	ListFilesParamsSortByMimeType  ListFilesParamsSortBy = "mime_type"
	ListFilesParamsSortByName      ListFilesParamsSortBy = "name"
	ListFilesParamsSortBySize      ListFilesParamsSortBy = "size"
	ListFilesParamsSortByStatus    ListFilesParamsSortBy = "status"
	ListFilesParamsSortByUpdatedAt ListFilesParamsSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSortBy enum.
func (e ListFilesParamsSortBy) Valid() bool {
	switch e {
	case ListFilesParamsSortByCreatedAt:
		return true
	case ListFilesParamsSortByMimeType:
		return true
	case ListFilesParamsSortByName:
		return true
	case ListFilesParamsSortBySize:
		return true
	case ListFilesParamsSortByStatus:
		return true
	case ListFilesParamsSortByUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListFilesParamsSortDir.
const (
	ListFilesParamsSortDirAsc  ListFilesParamsSortDir = "asc"
	ListFilesParamsSortDirDesc ListFilesParamsSortDir = "desc"
)

// Valid indicates whether the value is a known member of the ListFilesParamsSortDir enum.
func (e ListFilesParamsSortDir) Valid() bool {
	switch e {
	case ListFilesParamsSortDirAsc:
		return true
	case ListFilesParamsSortDirDesc:
		return true
	default:
		return false
	}
}

// AppError Standardized error response structure matching application error domains
type AppError struct {
	Code    int                `json:"code"`
	Details *map[string]string `json:"details,omitempty"`
	Message string             `json:"message"`
	Status  string             `json:"status"`
}

// CourseDetailResponse A course with its school summary and the full list of sections
type CourseDetailResponse struct {
	CreatedAt   time.Time          `json:"created_at"`
	Department  string             `json:"department"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Number      string             `json:"number"`

	// School Compact school payload embedded inside other resources (courses, study guides)
	School   SchoolSummary    `json:"school"`
	Sections []SectionSummary `json:"sections"`
	Title    string           `json:"title"`
}

// CourseResponse A course (e.g. CPTS 322) with its school summary embedded
type CourseResponse struct {
	CreatedAt   time.Time          `json:"created_at"`
	Department  string             `json:"department"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Number      string             `json:"number"`

	// School Compact school payload embedded inside other resources (courses, study guides)
	School SchoolSummary `json:"school"`
	Title  string        `json:"title"`
}

// CreateFileRequest Payload to create a new file reference
type CreateFileRequest struct {
	MimeType CreateFileRequestMimeType `json:"mime_type"`
	Name     string                    `json:"name"`
	Size     int64                     `json:"size"`
}

// CreateFileRequestMimeType defines model for CreateFileRequest.MimeType.
type CreateFileRequestMimeType string

// CreateFileResponse Created file reference with a presigned upload URL
type CreateFileResponse struct {
	// File Complete metadata payload describing an uploaded file
	File      FileResponse `json:"file"`
	UploadUrl string       `json:"upload_url"`
}

// CreateGrantRequest Request body for creating a file grant
type CreateGrantRequest struct {
	GranteeId   openapi_types.UUID            `json:"grantee_id"`
	GranteeType CreateGrantRequestGranteeType `json:"grantee_type"`
	Permission  CreateGrantRequestPermission  `json:"permission"`
}

// CreateGrantRequestGranteeType defines model for CreateGrantRequest.GranteeType.
type CreateGrantRequestGranteeType string

// CreateGrantRequestPermission defines model for CreateGrantRequest.Permission.
type CreateGrantRequestPermission string

// FileResponse Complete metadata payload describing an uploaded file
type FileResponse struct {
	CreatedAt    time.Time          `json:"created_at"`
	FavoritedAt  *time.Time         `json:"favorited_at,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	LastViewedAt *time.Time         `json:"last_viewed_at,omitempty"`
	MimeType     string             `json:"mime_type"`
	Name         string             `json:"name"`
	Size         int64              `json:"size"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// GrantResponse A file permission grant
type GrantResponse struct {
	CreatedAt   time.Time          `json:"created_at"`
	FileId      openapi_types.UUID `json:"file_id"`
	GrantedBy   openapi_types.UUID `json:"granted_by"`
	GranteeId   openapi_types.UUID `json:"grantee_id"`
	GranteeType string             `json:"grantee_type"`
	Id          openapi_types.UUID `json:"id"`
	Permission  string             `json:"permission"`
}

// ListCoursesResponse A paginated collection of courses
type ListCoursesResponse struct {
	Courses    []CourseResponse `json:"courses"`
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor,omitempty"`
}

// ListFilesResponse A paginated collection of files
type ListFilesResponse struct {
	Files      []FileResponse `json:"files"`
	HasMore    bool           `json:"has_more"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// ListSchoolsResponse A paginated collection of schools
type ListSchoolsResponse struct {
	HasMore    bool             `json:"has_more"`
	NextCursor *string          `json:"next_cursor,omitempty"`
	Schools    []SchoolResponse `json:"schools"`
}

// RevokeGrantRequest Request body for revoking a file grant
type RevokeGrantRequest struct {
	GranteeId   openapi_types.UUID            `json:"grantee_id"`
	GranteeType RevokeGrantRequestGranteeType `json:"grantee_type"`
	Permission  RevokeGrantRequestPermission  `json:"permission"`
}

// RevokeGrantRequestGranteeType defines model for RevokeGrantRequest.GranteeType.
type RevokeGrantRequestGranteeType string

// RevokeGrantRequestPermission defines model for RevokeGrantRequest.Permission.
type RevokeGrantRequestPermission string

// SchoolResponse A school (university or college)
type SchoolResponse struct {
	Acronym string  `json:"acronym"`
	City    *string `json:"city,omitempty"`

	// Country ISO 3166-1 alpha-2 country code
	Country   *string            `json:"country,omitempty"`
	CreatedAt time.Time          `json:"created_at"`
	Domain    *string            `json:"domain,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	State     *string            `json:"state,omitempty"`
	Url       *string            `json:"url,omitempty"`
}

// SchoolSummary Compact school payload embedded inside other resources (courses, study guides)
type SchoolSummary struct {
	Acronym string  `json:"acronym"`
	City    *string `json:"city,omitempty"`

	// Country ISO 3166-1 alpha-2 country code
	Country *string            `json:"country,omitempty"`
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	State   *string            `json:"state,omitempty"`
}

// SectionSummary A section of a course (term + instructor + roster size)
type SectionSummary struct {
	Id             openapi_types.UUID `json:"id"`
	InstructorName *string            `json:"instructor_name,omitempty"`
	MemberCount    int64              `json:"member_count"`
	SectionCode    *string            `json:"section_code,omitempty"`
	Term           string             `json:"term"`
}

// UpdateFileRequest Request body for updating file metadata
type UpdateFileRequest struct {
	Name string `json:"name"`
}

// BadRequest Standardized error response structure matching application error domains
type BadRequest = AppError

// Forbidden Standardized error response structure matching application error domains
type Forbidden = AppError

// InternalServerError Standardized error response structure matching application error domains
type InternalServerError = AppError

// NotFound Standardized error response structure matching application error domains
type NotFound = AppError

// Unauthorized Standardized error response structure matching application error domains
type Unauthorized = AppError

// ListCoursesParams defines parameters for ListCourses.
type ListCoursesParams struct {
	// SchoolId Filter by school UUID
	SchoolId *openapi_types.UUID `form:"school_id,omitempty" json:"school_id,omitempty"`

	// Department Exact department code match (case-insensitive, e.g. "CPTS")
	Department *string `form:"department,omitempty" json:"department,omitempty"`

	// Q Search term, matches against title (trigram), department, or number (case-insensitive)
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// SortBy Database column to sort the results by
	SortBy *ListCoursesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sorting direction (ascending or descending)
	SortDir *ListCoursesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// PageLimit Maximum number of courses to return per page
	PageLimit *int `form:"page_limit,omitempty" json:"page_limit,omitempty"`

	// Cursor Opaque pagination cursor token obtained from the previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListCoursesParamsSortBy defines parameters for ListCourses.
type ListCoursesParamsSortBy string

// ListCoursesParamsSortDir defines parameters for ListCourses.
type ListCoursesParamsSortDir string

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Scope Filter files by ownership or access level
	Scope *ListFilesParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Status Filter files by processing status
	Status *ListFilesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// MimeType Filter by precise document mime-type classification
	MimeType *ListFilesParamsMimeType `form:"mime_type,omitempty" json:"mime_type,omitempty"`

	// MinSize Minimum file size in bytes
	MinSize *int64 `form:"min_size,omitempty" json:"min_size,omitempty"`

	// MaxSize Maximum file size in bytes
	MaxSize *int64 `form:"max_size,omitempty" json:"max_size,omitempty"`

	// CreatedFrom Filter for files created on or after this UTC timestamp
	CreatedFrom *time.Time `form:"created_from,omitempty" json:"created_from,omitempty"`

	// CreatedTo Filter for files created on or before this UTC timestamp
	CreatedTo *time.Time `form:"created_to,omitempty" json:"created_to,omitempty"`

	// UpdatedFrom Filter for files updated on or after this UTC timestamp
	UpdatedFrom *time.Time `form:"updated_from,omitempty" json:"updated_from,omitempty"`

	// UpdatedTo Filter for files updated on or before this UTC timestamp
	UpdatedTo *time.Time `form:"updated_to,omitempty" json:"updated_to,omitempty"`

	// Q Search term to partially match against file names
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// SortBy Database column to sort the results by
	SortBy *ListFilesParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sorting direction (ascending or descending)
	SortDir *ListFilesParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`

	// PageLimit Maximum number of files to return per page
	PageLimit *int `form:"page_limit,omitempty" json:"page_limit,omitempty"`

	// Cursor Opaque pagination cursor token obtained from the previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListFilesParamsScope defines parameters for ListFiles.
type ListFilesParamsScope string

// ListFilesParamsStatus defines parameters for ListFiles.
type ListFilesParamsStatus string

// ListFilesParamsMimeType defines parameters for ListFiles.
type ListFilesParamsMimeType string

// ListFilesParamsSortBy defines parameters for ListFiles.
type ListFilesParamsSortBy string

// ListFilesParamsSortDir defines parameters for ListFiles.
type ListFilesParamsSortDir string

// ListSchoolsParams defines parameters for ListSchools.
type ListSchoolsParams struct {
	// Q Search term, partial match against school name (trigram) or exact match against acronym (case-insensitive)
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// PageLimit Maximum number of schools to return per page
	PageLimit *int `form:"page_limit,omitempty" json:"page_limit,omitempty"`

	// Cursor Opaque pagination cursor token obtained from the previous response
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateFileJSONRequestBody defines body for CreateFile for application/json ContentType.
type CreateFileJSONRequestBody = CreateFileRequest

// UpdateFileJSONRequestBody defines body for UpdateFile for application/json ContentType.
type UpdateFileJSONRequestBody = UpdateFileRequest

// RevokeGrantJSONRequestBody defines body for RevokeGrant for application/json ContentType.
type RevokeGrantJSONRequestBody = RevokeGrantRequest

// CreateGrantJSONRequestBody defines body for CreateGrant for application/json ContentType.
type CreateGrantJSONRequestBody = CreateGrantRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List and search courses
	// (GET /courses)
	ListCourses(w http.ResponseWriter, r *http.Request, params ListCoursesParams)
	// Get a course detail with embedded sections
	// (GET /courses/{course_id})
	GetCourse(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID)
	// Create a file reference and get a presigned upload URL
	// (POST /files)
	CreateFile(w http.ResponseWriter, r *http.Request)
	// Delete a file by ID
	// (DELETE /files/{file_id})
	DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Get a file by ID
	// (GET /files/{file_id})
	GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Rename a file
	// (PATCH /files/{file_id})
	UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Revoke a permission on a file
	// (DELETE /files/{file_id}/grants)
	RevokeGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Grant a permission on a file
	// (POST /files/{file_id}/grants)
	CreateGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// List files for the current user
	// (GET /me/files)
	ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams)
	// List and search schools
	// (GET /schools)
	ListSchools(w http.ResponseWriter, r *http.Request, params ListSchoolsParams)
	// Get a single school by ID
	// (GET /schools/{school_id})
	GetSchool(w http.ResponseWriter, r *http.Request, schoolId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List and search courses
// (GET /courses)
func (_ Unimplemented) ListCourses(w http.ResponseWriter, r *http.Request, params ListCoursesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a course detail with embedded sections
// (GET /courses/{course_id})
func (_ Unimplemented) GetCourse(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a file reference and get a presigned upload URL
// (POST /files)
func (_ Unimplemented) CreateFile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a file by ID
// (DELETE /files/{file_id})
func (_ Unimplemented) DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a file by ID
// (GET /files/{file_id})
func (_ Unimplemented) GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rename a file
// (PATCH /files/{file_id})
func (_ Unimplemented) UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a permission on a file
// (DELETE /files/{file_id}/grants)
func (_ Unimplemented) RevokeGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Grant a permission on a file
// (POST /files/{file_id}/grants)
func (_ Unimplemented) CreateGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List files for the current user
// (GET /me/files)
func (_ Unimplemented) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List and search schools
// (GET /schools)
func (_ Unimplemented) ListSchools(w http.ResponseWriter, r *http.Request, params ListSchoolsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a single school by ID
// (GET /schools/{school_id})
func (_ Unimplemented) GetSchool(w http.ResponseWriter, r *http.Request, schoolId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListCourses operation middleware
func (siw *ServerInterfaceWrapper) ListCourses(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCoursesParams

	// ------------- Optional query parameter "school_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "school_id", r.URL.Query(), &params.SchoolId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "school_id", Err: err})
		return
	}

	// ------------- Optional query parameter "department" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "department", r.URL.Query(), &params.Department, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "department", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_limit", r.URL.Query(), &params.PageLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCourses(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCourse operation middleware
func (siw *ServerInterfaceWrapper) GetCourse(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "course_id" -------------
	var courseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "course_id", chi.URLParam(r, "course_id"), &courseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "course_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCourse(w, r, courseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFile operation middleware
func (siw *ServerInterfaceWrapper) CreateFile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteFile operation middleware
func (siw *ServerInterfaceWrapper) DeleteFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFile operation middleware
func (siw *ServerInterfaceWrapper) GetFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateFile operation middleware
func (siw *ServerInterfaceWrapper) UpdateFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateFile(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeGrant operation middleware
func (siw *ServerInterfaceWrapper) RevokeGrant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeGrant(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGrant operation middleware
func (siw *ServerInterfaceWrapper) CreateGrant(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "file_id" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "file_id", chi.URLParam(r, "file_id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "file_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGrant(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFiles operation middleware
func (siw *ServerInterfaceWrapper) ListFiles(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFilesParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", r.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "mime_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mime_type", r.URL.Query(), &params.MimeType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mime_type", Err: err})
		return
	}

	// ------------- Optional query parameter "min_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_size", r.URL.Query(), &params.MinSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_size", Err: err})
		return
	}

	// ------------- Optional query parameter "max_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_size", r.URL.Query(), &params.MaxSize, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_size", Err: err})
		return
	}

	// ------------- Optional query parameter "created_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_from", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_from", Err: err})
		return
	}

	// ------------- Optional query parameter "created_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_to", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_to", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_from", r.URL.Query(), &params.UpdatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_from", Err: err})
		return
	}

	// ------------- Optional query parameter "updated_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "updated_to", r.URL.Query(), &params.UpdatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "updated_to", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_limit", r.URL.Query(), &params.PageLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchools operation middleware
func (siw *ServerInterfaceWrapper) ListSchools(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchoolsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "page_limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_limit", r.URL.Query(), &params.PageLimit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchools(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchool operation middleware
func (siw *ServerInterfaceWrapper) GetSchool(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "school_id" -------------
	var schoolId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "school_id", chi.URLParam(r, "school_id"), &schoolId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "school_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchool(w, r, schoolId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses", wrapper.ListCourses)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/courses/{course_id}", wrapper.GetCourse)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files", wrapper.CreateFile)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/files/{file_id}", wrapper.DeleteFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/files/{file_id}", wrapper.GetFile)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/files/{file_id}", wrapper.UpdateFile)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/files/{file_id}/grants", wrapper.RevokeGrant)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/{file_id}/grants", wrapper.CreateGrant)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/files", wrapper.ListFiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schools", wrapper.ListSchools)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schools/{school_id}", wrapper.GetSchool)
	})

	return r
}

type BadRequestJSONResponse AppError

type ForbiddenJSONResponse AppError

type InternalServerErrorJSONResponse AppError

type NotFoundJSONResponse AppError

type UnauthorizedJSONResponse AppError

type ListCoursesRequestObject struct {
	Params ListCoursesParams
}

type ListCoursesResponseObject interface {
	VisitListCoursesResponse(w http.ResponseWriter) error
}

type ListCourses200JSONResponse ListCoursesResponse

func (response ListCourses200JSONResponse) VisitListCoursesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListCourses400JSONResponse struct{ BadRequestJSONResponse }

func (response ListCourses400JSONResponse) VisitListCoursesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListCourses401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListCourses401JSONResponse) VisitListCoursesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListCourses500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListCourses500JSONResponse) VisitListCoursesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetCourseRequestObject struct {
	CourseId openapi_types.UUID `json:"course_id"`
}

type GetCourseResponseObject interface {
	VisitGetCourseResponse(w http.ResponseWriter) error
}

type GetCourse200JSONResponse CourseDetailResponse

func (response GetCourse200JSONResponse) VisitGetCourseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCourse400JSONResponse struct{ BadRequestJSONResponse }

func (response GetCourse400JSONResponse) VisitGetCourseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCourse401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCourse401JSONResponse) VisitGetCourseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCourse404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCourse404JSONResponse) VisitGetCourseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCourse500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetCourse500JSONResponse) VisitGetCourseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateFileRequestObject struct {
	Body *CreateFileJSONRequestBody
}

type CreateFileResponseObject interface {
	VisitCreateFileResponse(w http.ResponseWriter) error
}

type CreateFile201JSONResponse CreateFileResponse

func (response CreateFile201JSONResponse) VisitCreateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateFile400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateFile400JSONResponse) VisitCreateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateFile401JSONResponse) VisitCreateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateFile500JSONResponse) VisitCreateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
}

type DeleteFileResponseObject interface {
	VisitDeleteFileResponse(w http.ResponseWriter) error
}

type DeleteFile204Response struct {
}

func (response DeleteFile204Response) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteFile401JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteFile404JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteFile500JSONResponse) VisitDeleteFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
}

type GetFileResponseObject interface {
	VisitGetFileResponse(w http.ResponseWriter) error
}

type GetFile200JSONResponse FileResponse

func (response GetFile200JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetFile400JSONResponse struct{ BadRequestJSONResponse }

func (response GetFile400JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetFile401JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetFile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetFile403JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetFile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetFile404JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetFile500JSONResponse) VisitGetFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFileRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
	Body   *UpdateFileJSONRequestBody
}

type UpdateFileResponseObject interface {
	VisitUpdateFileResponse(w http.ResponseWriter) error
}

type UpdateFile200JSONResponse FileResponse

func (response UpdateFile200JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateFile400JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateFile401JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateFile404JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateFile500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateFile500JSONResponse) VisitUpdateFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RevokeGrantRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
	Body   *RevokeGrantJSONRequestBody
}

type RevokeGrantResponseObject interface {
	VisitRevokeGrantResponse(w http.ResponseWriter) error
}

type RevokeGrant204Response struct {
}

func (response RevokeGrant204Response) VisitRevokeGrantResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeGrant400JSONResponse struct{ BadRequestJSONResponse }

func (response RevokeGrant400JSONResponse) VisitRevokeGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RevokeGrant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RevokeGrant401JSONResponse) VisitRevokeGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevokeGrant404JSONResponse struct{ NotFoundJSONResponse }

func (response RevokeGrant404JSONResponse) VisitRevokeGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeGrant500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response RevokeGrant500JSONResponse) VisitRevokeGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateGrantRequestObject struct {
	FileId openapi_types.UUID `json:"file_id"`
	Body   *CreateGrantJSONRequestBody
}

type CreateGrantResponseObject interface {
	VisitCreateGrantResponse(w http.ResponseWriter) error
}

type CreateGrant201JSONResponse GrantResponse

func (response CreateGrant201JSONResponse) VisitCreateGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGrant400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGrant400JSONResponse) VisitCreateGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGrant401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGrant401JSONResponse) VisitCreateGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGrant404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateGrant404JSONResponse) VisitCreateGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateGrant500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateGrant500JSONResponse) VisitCreateGrantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListFilesRequestObject struct {
	Params ListFilesParams
}

type ListFilesResponseObject interface {
	VisitListFilesResponse(w http.ResponseWriter) error
}

type ListFiles200JSONResponse ListFilesResponse

func (response ListFiles200JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles400JSONResponse struct{ BadRequestJSONResponse }

func (response ListFiles400JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListFiles401JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListFiles500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListFiles500JSONResponse) VisitListFilesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListSchoolsRequestObject struct {
	Params ListSchoolsParams
}

type ListSchoolsResponseObject interface {
	VisitListSchoolsResponse(w http.ResponseWriter) error
}

type ListSchools200JSONResponse ListSchoolsResponse

func (response ListSchools200JSONResponse) VisitListSchoolsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListSchools400JSONResponse struct{ BadRequestJSONResponse }

func (response ListSchools400JSONResponse) VisitListSchoolsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListSchools401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSchools401JSONResponse) VisitListSchoolsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListSchools500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListSchools500JSONResponse) VisitListSchoolsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSchoolRequestObject struct {
	SchoolId openapi_types.UUID `json:"school_id"`
}

type GetSchoolResponseObject interface {
	VisitGetSchoolResponse(w http.ResponseWriter) error
}

type GetSchool200JSONResponse SchoolResponse

func (response GetSchool200JSONResponse) VisitGetSchoolResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSchool400JSONResponse struct{ BadRequestJSONResponse }

func (response GetSchool400JSONResponse) VisitGetSchoolResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSchool401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetSchool401JSONResponse) VisitGetSchoolResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetSchool404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSchool404JSONResponse) VisitGetSchoolResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSchool500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetSchool500JSONResponse) VisitGetSchoolResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List and search courses
	// (GET /courses)
	ListCourses(ctx context.Context, request ListCoursesRequestObject) (ListCoursesResponseObject, error)
	// Get a course detail with embedded sections
	// (GET /courses/{course_id})
	GetCourse(ctx context.Context, request GetCourseRequestObject) (GetCourseResponseObject, error)
	// Create a file reference and get a presigned upload URL
	// (POST /files)
	CreateFile(ctx context.Context, request CreateFileRequestObject) (CreateFileResponseObject, error)
	// Delete a file by ID
	// (DELETE /files/{file_id})
	DeleteFile(ctx context.Context, request DeleteFileRequestObject) (DeleteFileResponseObject, error)
	// Get a file by ID
	// (GET /files/{file_id})
	GetFile(ctx context.Context, request GetFileRequestObject) (GetFileResponseObject, error)
	// Rename a file
	// (PATCH /files/{file_id})
	UpdateFile(ctx context.Context, request UpdateFileRequestObject) (UpdateFileResponseObject, error)
	// Revoke a permission on a file
	// (DELETE /files/{file_id}/grants)
	RevokeGrant(ctx context.Context, request RevokeGrantRequestObject) (RevokeGrantResponseObject, error)
	// Grant a permission on a file
	// (POST /files/{file_id}/grants)
	CreateGrant(ctx context.Context, request CreateGrantRequestObject) (CreateGrantResponseObject, error)
	// List files for the current user
	// (GET /me/files)
	ListFiles(ctx context.Context, request ListFilesRequestObject) (ListFilesResponseObject, error)
	// List and search schools
	// (GET /schools)
	ListSchools(ctx context.Context, request ListSchoolsRequestObject) (ListSchoolsResponseObject, error)
	// Get a single school by ID
	// (GET /schools/{school_id})
	GetSchool(ctx context.Context, request GetSchoolRequestObject) (GetSchoolResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListCourses operation middleware
func (sh *strictHandler) ListCourses(w http.ResponseWriter, r *http.Request, params ListCoursesParams) {
	var request ListCoursesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCourses(ctx, request.(ListCoursesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCourses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCoursesResponseObject); ok {
		if err := validResponse.VisitListCoursesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCourse operation middleware
func (sh *strictHandler) GetCourse(w http.ResponseWriter, r *http.Request, courseId openapi_types.UUID) {
	var request GetCourseRequestObject

	request.CourseId = courseId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCourse(ctx, request.(GetCourseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCourse")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCourseResponseObject); ok {
		if err := validResponse.VisitGetCourseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateFile operation middleware
func (sh *strictHandler) CreateFile(w http.ResponseWriter, r *http.Request) {
	var request CreateFileRequestObject

	var body CreateFileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateFile(ctx, request.(CreateFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateFileResponseObject); ok {
		if err := validResponse.VisitCreateFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteFile operation middleware
func (sh *strictHandler) DeleteFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request DeleteFileRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteFile(ctx, request.(DeleteFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteFileResponseObject); ok {
		if err := validResponse.VisitDeleteFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetFile operation middleware
func (sh *strictHandler) GetFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request GetFileRequestObject

	request.FileId = fileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFile(ctx, request.(GetFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFileResponseObject); ok {
		if err := validResponse.VisitGetFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateFile operation middleware
func (sh *strictHandler) UpdateFile(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request UpdateFileRequestObject

	request.FileId = fileId

	var body UpdateFileJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateFile(ctx, request.(UpdateFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateFile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateFileResponseObject); ok {
		if err := validResponse.VisitUpdateFileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeGrant operation middleware
func (sh *strictHandler) RevokeGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request RevokeGrantRequestObject

	request.FileId = fileId

	var body RevokeGrantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeGrant(ctx, request.(RevokeGrantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeGrant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeGrantResponseObject); ok {
		if err := validResponse.VisitRevokeGrantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGrant operation middleware
func (sh *strictHandler) CreateGrant(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	var request CreateGrantRequestObject

	request.FileId = fileId

	var body CreateGrantJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGrant(ctx, request.(CreateGrantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGrant")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGrantResponseObject); ok {
		if err := validResponse.VisitCreateGrantResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFiles operation middleware
func (sh *strictHandler) ListFiles(w http.ResponseWriter, r *http.Request, params ListFilesParams) {
	var request ListFilesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFiles(ctx, request.(ListFilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFilesResponseObject); ok {
		if err := validResponse.VisitListFilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListSchools operation middleware
func (sh *strictHandler) ListSchools(w http.ResponseWriter, r *http.Request, params ListSchoolsParams) {
	var request ListSchoolsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSchools(ctx, request.(ListSchoolsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSchools")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSchoolsResponseObject); ok {
		if err := validResponse.VisitListSchoolsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchool operation middleware
func (sh *strictHandler) GetSchool(w http.ResponseWriter, r *http.Request, schoolId openapi_types.UUID) {
	var request GetSchoolRequestObject

	request.SchoolId = schoolId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchool(ctx, request.(GetSchoolRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchool")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSchoolResponseObject); ok {
		if err := validResponse.VisitGetSchoolResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcXXPbNtb+Kxi+74UzZSzbcbI7unOTuuOdbpuJ7dmLNqOBiCMJLQkwAGhb8ei/7+AA",
	"kEgKlCivotSTXEUk8XFwzoPz7TwmmSxKKUAYnQwfEwW6lEIDPvxI2Qf4VIE29imTwoDAn7Qsc55Rw6UY",
	"/KmlsO90NoOC2l//r2CSDJP/G6yWHrivenBRlj8pJVWyWCzShIHOFC/tOsnQbkeU32+RJpdSjTljIA6y",
	"+Wq3RZpcCQNK0Pwa1B0oN+cQRIR9icaNCbiBafKrNJeyEuwgVPwqDZngbos0uRW0MjOp+Gc4zO6NDe1n",
	"P8muuZw3fGzNujZUMKqYneXYRgKUiTaqykylgBTUZDMupqRGuh/NZEG50EmalEqWoAx3dyCTDOy/Zl5C",
	"Mky4MDAFlAkDQ3mOgyhj3K5F8/eNyX6SNoqLqZ3jX8jxn5AhyAvQmk4hOlgbaqrYOos0sfeEKyuS3x2J",
	"y+GrNT9G9nsrK6XhHZL+wTNonZsXJMNx5J6bGeFGE53NpMyJroqCqjmhghEzAzKp8pzkXBsiJ0RDZudH",
	"eKiAGmAjirCZSFXYXwmjBl4aXlji1w7PoKTKFB5qkc81eh8TUeU5HeeQDI2qILIcZ42tq4qz2K6iKsag",
	"4tJADmxD9jWOunZswmmBKcPHhBso9NYV3ITaEp4UqhR1z9zksB0WeEJPdYOfy2OGpdK6hGokdwOoB3SO",
	"4Hh6TN6+v7kmr87OXnRCCYoxMAbsO2rqIv+iIo7KFT9f8hxqJr8p2vd0nkvKiJHELUYoEXBPJjwHomAC",
	"CkQGa3IseAEjt99jAqIqkPKCTmHwZwnTJPUPpVj9vodxmaQNC1OySevNnWDHsgTxUORORPqlnEx4Bkxm",
	"lWXD8b1UrFQyA625mBb5cfiy80qlAg3C4PAibzxaHsODGZQ55aK1MJTV+IfPvKyxvAYbWiBPCvrwC4ip",
	"mSXDs9ev06TgIjyfRqZp/hkasOTCvDm3ep8+8MKy9/Tk/J+v//Hm5ATX8u/SNRPWAhOSk9bE5bfahpYu",
	"TeDGsBY8nB6gxHKQTwUwUpWIqtsPv6xBx07ddncaRCzSxC03qlS+/f7g+o0p3Yf9WVFhOu+G/0DGks3J",
	"RCp3Q9DVcAyY2ulrB8S3AKOeiiYMb9+mSuNVd5oXXYGKzUfTijOIIq8EVXCtvRoMq9xxuLeTZ1QBqpMc",
	"TGx+i4kNotL6kRobxTi7BUCyKC0JpABDGTWUlF4DuXFjZK/wAPJI24sZmdA7qfiWWfuyHjnVZmR5/z9u",
	"19CzncqmvzpZ93g7HVJ7hdiOXI6ZMq+CkKSWJgrObcNTqe0ag5e/st2uCt7MFUY7LumTEMTzHW81G43n",
	"OymBJ+qMp8K0qTN6CDOwIO2rIRqc2Oqw/MK1cc6o3iTikk65QDuUyTx3nq0NVpyujMV77n1fd73lD0fc",
	"9RnVo0KqOvPHUuZAMdUg4MGMskppF9VuueVrkV84xHKTLlZZVfskRlkx6qhl7s+kto0+IIsC+VsZ5Hzw",
	"J7HIeeDrTNrnsYKfv0MgieO72d5i1OoQG1n1Ae7kX7s6Q8pO+u4MbXaGWvKK4M9HzkeV4HegNDdzYj1N",
	"i8UpvFjjJ82UFPMiqvQzbua9UJfJShg1Xyfn6vo38ur0zZuXp4Tm5Yy+PCN+LPEJqXpc08N/eVK8j1m7",
	"vcbynX6SoQZ67eRDj930VN3/CYLbagObeYOoA00zE3ATvOeQcSFcaM6ASDMDTJfKSmWgyZE3KynBq0Pw",
	"6uhnj69DAaCHYKOybOb9Ytd/ZXHoMstmQBXkBytKzHJLRX4gSmoDilg3el1qPdmwWnAUOLI9ArHIUiMU",
	"UzxDEbIRJ9Hwwp1vFFLuW/ezZ+/pjOLQFoUxKdxiRLExDbZm3TAKsdYNbVsIVtcY/6R0TyxHs063Y16l",
	"uJlfW+vvy3dAFaiLyq78mIzx6TKI5F//uUl8bQX9Evy6AsLMmNJVZ7iYSGSyS0kmF/qvC5NTTS7eXyVp",
	"goYI+XJ6fHJ8YnkoSxC05MkweXV8cvzKMoKaGZI0qLnXU0DmWhZhsuyKJcO6V4/zFC3AgNLJ8Pe2HC55",
	"blE+ngf9dnt79S6xBCfD5FMFah4u3tA7N6OQL/Ulqi2XYJG2t/zpwarTVZ4VNZGrKpGjjGp4yYUGobnh",
	"d5ASzID/kbx9f3P9R/Kig7RG1nZFWx0lJz1IuwaqshmxOE8dRaAJnVJ7jwnKjhwZxaeKFi/S2hFS60K4",
	"ZPH6Ebpo/tRNah9a31FDx1SDdV2qQhAjiZbKYEVJga5yowmGgFFRSmVcgLiigMGEVrlpczP4ck9IjG9g",
	"tFR42RlXXh8fUZ2BYPalVJibck8vNp2AcdVxBKqzGu3uyS7ai7p/uxxwkOgq0LVMVmAqJUgJyoYy0EGe",
	"/TTKecFNnMCz141U89Ykc5vE30r6qYIQTFkGuiCIGPkXCCLHhnIBjEyULBASpYI7Liu9rOh2EO5jqTrR",
	"bX59TJsdDmcnJ3srascSEpH6dj2MDJXTICPMjS/ds0ahzBqRRZqcO4JjdCwPNqj1beCU0+1TmlX3NHnd",
	"Z59YmwTaouDDoDrHYrF26imofzsq2ILBo/sx4mzRaRd+Bs/bbVbhZgakEtwizNoDy12LoWU0iMCx9qiG",
	"m7B9Uje2zufobyy+JLSiVfsItm5QgaLkMUmxquHHQTX3svH13gPi6/zkfPukZdfL/gD5M5iV8+w6ONoM",
	"WnLDYnSZ5yqljsByVQfz2AFtfpRsvj/Jr5VlF02f0MJ0sQa90y9CQDfwLps1Pm9SHWejlb7np8rehpJ3",
	"q55pb9AUURU/6BJFg0efEV84c4oJpTVEvcP3HlE7aToFviptHRFszrGEGkn8VlHdt0rS71Pzna9HTYgQ",
	"XWUZaD2p8nxOPlVQWTOPPlMOOO65qRMnrQCK8ZxcvcPUZIcJ25tYDynM/ZmxbVrEFeQOa4ZebZ/UaA39",
	"uoarCbPShnnrQFvlMPamQlyh9Qujbv/Wcz2b08t6Hg7xjkD2FXD/dVD8ASxoPJCjtnGAJRO9yUTWSlBP",
	"jAYCrLEuBYSiVcKA89lBPFKP64XxiInGRTxPGDmydpkzIqQh8MC1efFtANQhot4VIsUSsOnGOGAfkET4",
	"B0Qa+ezwGGmWO3DE0uz6iShdh/MQo1ic01wBZXOHc2DfBNIdF7qAbjVzAavwtzNZfxnaQ3qk6nE1677I",
	"ewFKz3hJLPMd1nO4g7wzfS9dF1gkXWrXYrWEaXiO1v/TxO3Gxzn0yqe2KV91E5NlS1qU4vAxRnLmGxtr",
	"VJcuZYx0Lz9OKM+B7UInUggZ10BC6zIpeAEv7QIky6nWfOKvVQflja67JfHf+7Y35Nxd+tupcM0/A+GC",
	"jOcGdCeLxcj3OEb0dZ9iaXfivz8R9GHvRITbIsONCUrWKhdF6MR+NTOuye3NW2J4AdrQouzK5/vCjPfL",
	"IlRubC/dkbgxTKSC3alDG7132nxn69MYF9pivxTjmsTtyrhA3V4YVyt7Wu+ppMpwmudzX5QNBVC8FXZ/",
	"3aui+TUrmLWe5pV5aLxstEA3W6ZXfwO41OJ/i5om1i/3WNR0OPxe0jxASbPZOBzN2oUypvMWn2mV0kHK",
	"KjmsF1ZKWecJm0nRG66133Y6w9erRuBN7nCjV8OrrJbC8mU6zJYs+zbsVQRsQWkO9m1lB+vfWL+Pnjnf",
	"b+QhbmS7U71nk0EA8PPvIliepHYvB4/LHq+NXQTX4a9ln5KkWf6pbSQnU28x+3uWX9p/ELCtf8Cf9pvp",
	"CrCxZh6EHKos9d5KBEq9q/L3j1Zg7j/rcDDC3u9kQEueLD4u/hsAAP//kBvdhV5FAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
