// Package api provides the HTTP handlers, structural models, and OpenAPI bindings for the application.
package api

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/Ask-Atlas/AskAtlas/api/pkg/apperrors"
	"github.com/getkin/kin-openapi/openapi3filter"
)

// BearerAuthFunc enforces the spec-declared security scheme without
// re-verifying the token. It asserts the operation uses an HTTP bearer
// scheme and carries an Authorization: Bearer header. JWT verification
// is performed upstream by the clerkAuth middleware; this function
// exists so the validator fails loudly if a new operation is added
// with an unsupported scheme or missing Authorization header.
func BearerAuthFunc(_ context.Context, input *openapi3filter.AuthenticationInput) error {
	scheme := input.SecurityScheme
	if scheme == nil || scheme.Type != "http" || !strings.EqualFold(scheme.Scheme, "bearer") {
		return fmt.Errorf("unsupported security scheme %q", input.SecuritySchemeName)
	}
	header := input.RequestValidationInput.Request.Header.Get("Authorization")
	if header == "" {
		return fmt.Errorf("missing Authorization header")
	}
	const prefix = "Bearer "
	if len(header) <= len(prefix) || !strings.EqualFold(header[:len(prefix)], prefix) {
		return fmt.Errorf("Authorization header must use Bearer scheme")
	}
	return nil
}

var paramErrorRegex = regexp.MustCompile(`^parameter "([^"]+)"(?: in [^ ]+)? has an error: (.+)$`)

// OAPIValidatorErrorHandler is a custom ErrorHandler for the OpenAPI request validator middleware.
func OAPIValidatorErrorHandler(w http.ResponseWriter, message string, statusCode int) {
	var details map[string]string
	if statusCode == http.StatusBadRequest {
		matches := paramErrorRegex.FindStringSubmatch(message)
		if len(matches) == 3 {
			details = map[string]string{}
			field := matches[1]
			errMsg := matches[2]
			details[field] = errMsg
		} else {
			details = map[string]string{}
			details["validation"] = message
		}
	}

	err := &apperrors.AppError{
		Code:    statusCode,
		Status:  http.StatusText(statusCode),
		Message: "Invalid request parameters",
		Details: details,
	}
	apperrors.RespondWithError(w, err)
}

// OAPIStrictErrorHandler handles binding errors from the structural request parsing generated by oapi-codegen.
func OAPIStrictErrorHandler(w http.ResponseWriter, r *http.Request, err error) {
	details := map[string]string{}
	switch e := err.(type) {
	case *InvalidParamFormatError:
		details[e.ParamName] = e.Err.Error()
	case *UnmarshalingParamError:
		details[e.ParamName] = e.Err.Error()
	case *RequiredParamError:
		details[e.ParamName] = "is required"
	case *RequiredHeaderError:
		details[e.ParamName] = "is required"
	case *UnescapedCookieParamError:
		details[e.ParamName] = e.Err.Error()
	case *TooManyValuesForParamError:
		details[e.ParamName] = "expected one value"
	default:
		details["validation"] = err.Error()
	}

	appErr := &apperrors.AppError{
		Code:    http.StatusBadRequest,
		Status:  http.StatusText(http.StatusBadRequest),
		Message: "Invalid request parameters",
		Details: details,
	}
	apperrors.RespondWithError(w, appErr)
}
