// Package api provides the HTTP handlers, structural models, and OpenAPI bindings for the application.
package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/Ask-Atlas/AskAtlas/api/pkg/apperrors"
	"github.com/getkin/kin-openapi/openapi3filter"
)

// BearerAuthFunc is an openapi3filter.AuthenticationFunc that asserts the
// operation's security scheme is HTTP bearer and that an Authorization:
// Bearer header is present. It does not verify the token.
func BearerAuthFunc(_ context.Context, input *openapi3filter.AuthenticationInput) error {
	scheme := input.SecurityScheme
	if scheme == nil || scheme.Type != "http" || !strings.EqualFold(scheme.Scheme, "bearer") {
		return fmt.Errorf("unsupported security scheme %q", input.SecuritySchemeName)
	}
	header := input.RequestValidationInput.Request.Header.Get("Authorization")
	if header == "" {
		return errors.New("missing Authorization header")
	}
	const prefix = "Bearer "
	if len(header) <= len(prefix) || !strings.EqualFold(header[:len(prefix)], prefix) {
		return errors.New("Authorization header must use Bearer scheme")
	}
	return nil
}

var paramErrorRegex = regexp.MustCompile(`^parameter "([^"]+)"(?: in [^ ]+)? has an error: (.+)$`)

// bodyErrorRegex matches openapi3filter's request-body error format,
// e.g. `request body has an error: ...: Error at "/grantee_type": <msg>`.
// Captures the JSON pointer segment and the trailing message so we
// can surface field-keyed details instead of a catch-all "validation".
var bodyErrorRegex = regexp.MustCompile(`Error at "/([^"]+)": (.+)$`)

// OAPIValidatorErrorHandler is a custom ErrorHandler for the OpenAPI request validator middleware.
func OAPIValidatorErrorHandler(w http.ResponseWriter, message string, statusCode int) {
	var details map[string]string
	if statusCode == http.StatusBadRequest {
		details = map[string]string{}
		if matches := paramErrorRegex.FindStringSubmatch(message); len(matches) == 3 {
			details[matches[1]] = matches[2]
		} else if matches := bodyErrorRegex.FindStringSubmatch(message); len(matches) == 3 {
			details[matches[1]] = matches[2]
		} else {
			details["validation"] = message
		}
	}

	err := &apperrors.AppError{
		Code:    statusCode,
		Message: "Invalid request parameters",
		Details: details,
	}
	apperrors.RespondWithError(w, err)
}

// OAPIStrictErrorHandler handles binding errors from the structural request parsing generated by oapi-codegen.
func OAPIStrictErrorHandler(w http.ResponseWriter, r *http.Request, err error) {
	details := map[string]string{}
	switch e := err.(type) {
	case *InvalidParamFormatError:
		details[e.ParamName] = e.Err.Error()
	case *UnmarshalingParamError:
		details[e.ParamName] = e.Err.Error()
	case *RequiredParamError:
		details[e.ParamName] = "is required"
	case *RequiredHeaderError:
		details[e.ParamName] = "is required"
	case *UnescapedCookieParamError:
		details[e.ParamName] = e.Err.Error()
	case *TooManyValuesForParamError:
		details[e.ParamName] = "expected one value"
	default:
		details["validation"] = err.Error()
	}

	appErr := &apperrors.AppError{
		Code:    http.StatusBadRequest,
		Message: "Invalid request parameters",
		Details: details,
	}
	apperrors.RespondWithError(w, appErr)
}
