// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_handlers

import (
	"context"

	"github.com/Ask-Atlas/AskAtlas/api/internal/studyguides"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAIEditStudyGuideReader creates a new instance of MockAIEditStudyGuideReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIEditStudyGuideReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIEditStudyGuideReader {
	mock := &MockAIEditStudyGuideReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIEditStudyGuideReader is an autogenerated mock type for the AIEditStudyGuideReader type
type MockAIEditStudyGuideReader struct {
	mock.Mock
}

type MockAIEditStudyGuideReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIEditStudyGuideReader) EXPECT() *MockAIEditStudyGuideReader_Expecter {
	return &MockAIEditStudyGuideReader_Expecter{mock: &_m.Mock}
}

// GetStudyGuide provides a mock function for the type MockAIEditStudyGuideReader
func (_mock *MockAIEditStudyGuideReader) GetStudyGuide(ctx context.Context, params studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetStudyGuide")
	}

	var r0 studyguides.StudyGuideDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.GetStudyGuideParams) studyguides.StudyGuideDetail); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.StudyGuideDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.GetStudyGuideParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIEditStudyGuideReader_GetStudyGuide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudyGuide'
type MockAIEditStudyGuideReader_GetStudyGuide_Call struct {
	*mock.Call
}

// GetStudyGuide is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.GetStudyGuideParams
func (_e *MockAIEditStudyGuideReader_Expecter) GetStudyGuide(ctx interface{}, params interface{}) *MockAIEditStudyGuideReader_GetStudyGuide_Call {
	return &MockAIEditStudyGuideReader_GetStudyGuide_Call{Call: _e.mock.On("GetStudyGuide", ctx, params)}
}

func (_c *MockAIEditStudyGuideReader_GetStudyGuide_Call) Run(run func(ctx context.Context, params studyguides.GetStudyGuideParams)) *MockAIEditStudyGuideReader_GetStudyGuide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.GetStudyGuideParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.GetStudyGuideParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAIEditStudyGuideReader_GetStudyGuide_Call) Return(studyGuideDetail studyguides.StudyGuideDetail, err error) *MockAIEditStudyGuideReader_GetStudyGuide_Call {
	_c.Call.Return(studyGuideDetail, err)
	return _c
}

func (_c *MockAIEditStudyGuideReader_GetStudyGuide_Call) RunAndReturn(run func(ctx context.Context, params studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error)) *MockAIEditStudyGuideReader_GetStudyGuide_Call {
	_c.Call.Return(run)
	return _c
}
