// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_handlers

import (
	"context"

	"github.com/Ask-Atlas/AskAtlas/api/internal/studyguides"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStudyGuideGrantService creates a new instance of MockStudyGuideGrantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudyGuideGrantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudyGuideGrantService {
	mock := &MockStudyGuideGrantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStudyGuideGrantService is an autogenerated mock type for the StudyGuideGrantService type
type MockStudyGuideGrantService struct {
	mock.Mock
}

type MockStudyGuideGrantService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudyGuideGrantService) EXPECT() *MockStudyGuideGrantService_Expecter {
	return &MockStudyGuideGrantService_Expecter{mock: &_m.Mock}
}

// CreateGrant provides a mock function for the type MockStudyGuideGrantService
func (_mock *MockStudyGuideGrantService) CreateGrant(ctx context.Context, params studyguides.CreateGrantParams) (studyguides.Grant, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateGrant")
	}

	var r0 studyguides.Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CreateGrantParams) (studyguides.Grant, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CreateGrantParams) studyguides.Grant); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.Grant)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.CreateGrantParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideGrantService_CreateGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGrant'
type MockStudyGuideGrantService_CreateGrant_Call struct {
	*mock.Call
}

// CreateGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.CreateGrantParams
func (_e *MockStudyGuideGrantService_Expecter) CreateGrant(ctx interface{}, params interface{}) *MockStudyGuideGrantService_CreateGrant_Call {
	return &MockStudyGuideGrantService_CreateGrant_Call{Call: _e.mock.On("CreateGrant", ctx, params)}
}

func (_c *MockStudyGuideGrantService_CreateGrant_Call) Run(run func(ctx context.Context, params studyguides.CreateGrantParams)) *MockStudyGuideGrantService_CreateGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.CreateGrantParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.CreateGrantParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideGrantService_CreateGrant_Call) Return(grant studyguides.Grant, err error) *MockStudyGuideGrantService_CreateGrant_Call {
	_c.Call.Return(grant, err)
	return _c
}

func (_c *MockStudyGuideGrantService_CreateGrant_Call) RunAndReturn(run func(ctx context.Context, params studyguides.CreateGrantParams) (studyguides.Grant, error)) *MockStudyGuideGrantService_CreateGrant_Call {
	_c.Call.Return(run)
	return _c
}

// ListGrants provides a mock function for the type MockStudyGuideGrantService
func (_mock *MockStudyGuideGrantService) ListGrants(ctx context.Context, params studyguides.ListGrantsParams) ([]studyguides.Grant, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListGrants")
	}

	var r0 []studyguides.Grant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.ListGrantsParams) ([]studyguides.Grant, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.ListGrantsParams) []studyguides.Grant); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]studyguides.Grant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.ListGrantsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideGrantService_ListGrants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGrants'
type MockStudyGuideGrantService_ListGrants_Call struct {
	*mock.Call
}

// ListGrants is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.ListGrantsParams
func (_e *MockStudyGuideGrantService_Expecter) ListGrants(ctx interface{}, params interface{}) *MockStudyGuideGrantService_ListGrants_Call {
	return &MockStudyGuideGrantService_ListGrants_Call{Call: _e.mock.On("ListGrants", ctx, params)}
}

func (_c *MockStudyGuideGrantService_ListGrants_Call) Run(run func(ctx context.Context, params studyguides.ListGrantsParams)) *MockStudyGuideGrantService_ListGrants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.ListGrantsParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.ListGrantsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideGrantService_ListGrants_Call) Return(grants []studyguides.Grant, err error) *MockStudyGuideGrantService_ListGrants_Call {
	_c.Call.Return(grants, err)
	return _c
}

func (_c *MockStudyGuideGrantService_ListGrants_Call) RunAndReturn(run func(ctx context.Context, params studyguides.ListGrantsParams) ([]studyguides.Grant, error)) *MockStudyGuideGrantService_ListGrants_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeGrant provides a mock function for the type MockStudyGuideGrantService
func (_mock *MockStudyGuideGrantService) RevokeGrant(ctx context.Context, params studyguides.RevokeGrantParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RevokeGrant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.RevokeGrantParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudyGuideGrantService_RevokeGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeGrant'
type MockStudyGuideGrantService_RevokeGrant_Call struct {
	*mock.Call
}

// RevokeGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.RevokeGrantParams
func (_e *MockStudyGuideGrantService_Expecter) RevokeGrant(ctx interface{}, params interface{}) *MockStudyGuideGrantService_RevokeGrant_Call {
	return &MockStudyGuideGrantService_RevokeGrant_Call{Call: _e.mock.On("RevokeGrant", ctx, params)}
}

func (_c *MockStudyGuideGrantService_RevokeGrant_Call) Run(run func(ctx context.Context, params studyguides.RevokeGrantParams)) *MockStudyGuideGrantService_RevokeGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.RevokeGrantParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.RevokeGrantParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideGrantService_RevokeGrant_Call) Return(err error) *MockStudyGuideGrantService_RevokeGrant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudyGuideGrantService_RevokeGrant_Call) RunAndReturn(run func(ctx context.Context, params studyguides.RevokeGrantParams) error) *MockStudyGuideGrantService_RevokeGrant_Call {
	_c.Call.Return(run)
	return _c
}
