// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_handlers

import (
	"context"

	"github.com/Ask-Atlas/AskAtlas/api/internal/studyguides"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStudyGuideService creates a new instance of MockStudyGuideService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudyGuideService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudyGuideService {
	mock := &MockStudyGuideService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStudyGuideService is an autogenerated mock type for the StudyGuideService type
type MockStudyGuideService struct {
	mock.Mock
}

type MockStudyGuideService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudyGuideService) EXPECT() *MockStudyGuideService_Expecter {
	return &MockStudyGuideService_Expecter{mock: &_m.Mock}
}

// AssertCourseExists provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) AssertCourseExists(ctx context.Context, courseID uuid.UUID) error {
	ret := _mock.Called(ctx, courseID)

	if len(ret) == 0 {
		panic("no return value specified for AssertCourseExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, courseID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudyGuideService_AssertCourseExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertCourseExists'
type MockStudyGuideService_AssertCourseExists_Call struct {
	*mock.Call
}

// AssertCourseExists is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID uuid.UUID
func (_e *MockStudyGuideService_Expecter) AssertCourseExists(ctx interface{}, courseID interface{}) *MockStudyGuideService_AssertCourseExists_Call {
	return &MockStudyGuideService_AssertCourseExists_Call{Call: _e.mock.On("AssertCourseExists", ctx, courseID)}
}

func (_c *MockStudyGuideService_AssertCourseExists_Call) Run(run func(ctx context.Context, courseID uuid.UUID)) *MockStudyGuideService_AssertCourseExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_AssertCourseExists_Call) Return(err error) *MockStudyGuideService_AssertCourseExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudyGuideService_AssertCourseExists_Call) RunAndReturn(run func(ctx context.Context, courseID uuid.UUID) error) *MockStudyGuideService_AssertCourseExists_Call {
	_c.Call.Return(run)
	return _c
}

// CastVote provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) CastVote(ctx context.Context, params studyguides.CastVoteParams) (studyguides.CastVoteResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CastVote")
	}

	var r0 studyguides.CastVoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CastVoteParams) (studyguides.CastVoteResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CastVoteParams) studyguides.CastVoteResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.CastVoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.CastVoteParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideService_CastVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CastVote'
type MockStudyGuideService_CastVote_Call struct {
	*mock.Call
}

// CastVote is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.CastVoteParams
func (_e *MockStudyGuideService_Expecter) CastVote(ctx interface{}, params interface{}) *MockStudyGuideService_CastVote_Call {
	return &MockStudyGuideService_CastVote_Call{Call: _e.mock.On("CastVote", ctx, params)}
}

func (_c *MockStudyGuideService_CastVote_Call) Run(run func(ctx context.Context, params studyguides.CastVoteParams)) *MockStudyGuideService_CastVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.CastVoteParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.CastVoteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_CastVote_Call) Return(castVoteResult studyguides.CastVoteResult, err error) *MockStudyGuideService_CastVote_Call {
	_c.Call.Return(castVoteResult, err)
	return _c
}

func (_c *MockStudyGuideService_CastVote_Call) RunAndReturn(run func(ctx context.Context, params studyguides.CastVoteParams) (studyguides.CastVoteResult, error)) *MockStudyGuideService_CastVote_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStudyGuide provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) CreateStudyGuide(ctx context.Context, params studyguides.CreateStudyGuideParams) (studyguides.StudyGuideDetail, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateStudyGuide")
	}

	var r0 studyguides.StudyGuideDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CreateStudyGuideParams) (studyguides.StudyGuideDetail, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.CreateStudyGuideParams) studyguides.StudyGuideDetail); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.StudyGuideDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.CreateStudyGuideParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideService_CreateStudyGuide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStudyGuide'
type MockStudyGuideService_CreateStudyGuide_Call struct {
	*mock.Call
}

// CreateStudyGuide is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.CreateStudyGuideParams
func (_e *MockStudyGuideService_Expecter) CreateStudyGuide(ctx interface{}, params interface{}) *MockStudyGuideService_CreateStudyGuide_Call {
	return &MockStudyGuideService_CreateStudyGuide_Call{Call: _e.mock.On("CreateStudyGuide", ctx, params)}
}

func (_c *MockStudyGuideService_CreateStudyGuide_Call) Run(run func(ctx context.Context, params studyguides.CreateStudyGuideParams)) *MockStudyGuideService_CreateStudyGuide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.CreateStudyGuideParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.CreateStudyGuideParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_CreateStudyGuide_Call) Return(studyGuideDetail studyguides.StudyGuideDetail, err error) *MockStudyGuideService_CreateStudyGuide_Call {
	_c.Call.Return(studyGuideDetail, err)
	return _c
}

func (_c *MockStudyGuideService_CreateStudyGuide_Call) RunAndReturn(run func(ctx context.Context, params studyguides.CreateStudyGuideParams) (studyguides.StudyGuideDetail, error)) *MockStudyGuideService_CreateStudyGuide_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStudyGuide provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) DeleteStudyGuide(ctx context.Context, params studyguides.DeleteStudyGuideParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStudyGuide")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.DeleteStudyGuideParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudyGuideService_DeleteStudyGuide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStudyGuide'
type MockStudyGuideService_DeleteStudyGuide_Call struct {
	*mock.Call
}

// DeleteStudyGuide is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.DeleteStudyGuideParams
func (_e *MockStudyGuideService_Expecter) DeleteStudyGuide(ctx interface{}, params interface{}) *MockStudyGuideService_DeleteStudyGuide_Call {
	return &MockStudyGuideService_DeleteStudyGuide_Call{Call: _e.mock.On("DeleteStudyGuide", ctx, params)}
}

func (_c *MockStudyGuideService_DeleteStudyGuide_Call) Run(run func(ctx context.Context, params studyguides.DeleteStudyGuideParams)) *MockStudyGuideService_DeleteStudyGuide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.DeleteStudyGuideParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.DeleteStudyGuideParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_DeleteStudyGuide_Call) Return(err error) *MockStudyGuideService_DeleteStudyGuide_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudyGuideService_DeleteStudyGuide_Call) RunAndReturn(run func(ctx context.Context, params studyguides.DeleteStudyGuideParams) error) *MockStudyGuideService_DeleteStudyGuide_Call {
	_c.Call.Return(run)
	return _c
}

// GetStudyGuide provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) GetStudyGuide(ctx context.Context, params studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetStudyGuide")
	}

	var r0 studyguides.StudyGuideDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.GetStudyGuideParams) studyguides.StudyGuideDetail); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.StudyGuideDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.GetStudyGuideParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideService_GetStudyGuide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudyGuide'
type MockStudyGuideService_GetStudyGuide_Call struct {
	*mock.Call
}

// GetStudyGuide is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.GetStudyGuideParams
func (_e *MockStudyGuideService_Expecter) GetStudyGuide(ctx interface{}, params interface{}) *MockStudyGuideService_GetStudyGuide_Call {
	return &MockStudyGuideService_GetStudyGuide_Call{Call: _e.mock.On("GetStudyGuide", ctx, params)}
}

func (_c *MockStudyGuideService_GetStudyGuide_Call) Run(run func(ctx context.Context, params studyguides.GetStudyGuideParams)) *MockStudyGuideService_GetStudyGuide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.GetStudyGuideParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.GetStudyGuideParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_GetStudyGuide_Call) Return(studyGuideDetail studyguides.StudyGuideDetail, err error) *MockStudyGuideService_GetStudyGuide_Call {
	_c.Call.Return(studyGuideDetail, err)
	return _c
}

func (_c *MockStudyGuideService_GetStudyGuide_Call) RunAndReturn(run func(ctx context.Context, params studyguides.GetStudyGuideParams) (studyguides.StudyGuideDetail, error)) *MockStudyGuideService_GetStudyGuide_Call {
	_c.Call.Return(run)
	return _c
}

// ListStudyGuides provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) ListStudyGuides(ctx context.Context, params studyguides.ListStudyGuidesParams) (studyguides.ListStudyGuidesResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListStudyGuides")
	}

	var r0 studyguides.ListStudyGuidesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.ListStudyGuidesParams) (studyguides.ListStudyGuidesResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.ListStudyGuidesParams) studyguides.ListStudyGuidesResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(studyguides.ListStudyGuidesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, studyguides.ListStudyGuidesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStudyGuideService_ListStudyGuides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStudyGuides'
type MockStudyGuideService_ListStudyGuides_Call struct {
	*mock.Call
}

// ListStudyGuides is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.ListStudyGuidesParams
func (_e *MockStudyGuideService_Expecter) ListStudyGuides(ctx interface{}, params interface{}) *MockStudyGuideService_ListStudyGuides_Call {
	return &MockStudyGuideService_ListStudyGuides_Call{Call: _e.mock.On("ListStudyGuides", ctx, params)}
}

func (_c *MockStudyGuideService_ListStudyGuides_Call) Run(run func(ctx context.Context, params studyguides.ListStudyGuidesParams)) *MockStudyGuideService_ListStudyGuides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.ListStudyGuidesParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.ListStudyGuidesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_ListStudyGuides_Call) Return(listStudyGuidesResult studyguides.ListStudyGuidesResult, err error) *MockStudyGuideService_ListStudyGuides_Call {
	_c.Call.Return(listStudyGuidesResult, err)
	return _c
}

func (_c *MockStudyGuideService_ListStudyGuides_Call) RunAndReturn(run func(ctx context.Context, params studyguides.ListStudyGuidesParams) (studyguides.ListStudyGuidesResult, error)) *MockStudyGuideService_ListStudyGuides_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveVote provides a mock function for the type MockStudyGuideService
func (_mock *MockStudyGuideService) RemoveVote(ctx context.Context, params studyguides.RemoveVoteParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveVote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, studyguides.RemoveVoteParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStudyGuideService_RemoveVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveVote'
type MockStudyGuideService_RemoveVote_Call struct {
	*mock.Call
}

// RemoveVote is a helper method to define mock.On call
//   - ctx context.Context
//   - params studyguides.RemoveVoteParams
func (_e *MockStudyGuideService_Expecter) RemoveVote(ctx interface{}, params interface{}) *MockStudyGuideService_RemoveVote_Call {
	return &MockStudyGuideService_RemoveVote_Call{Call: _e.mock.On("RemoveVote", ctx, params)}
}

func (_c *MockStudyGuideService_RemoveVote_Call) Run(run func(ctx context.Context, params studyguides.RemoveVoteParams)) *MockStudyGuideService_RemoveVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 studyguides.RemoveVoteParams
		if args[1] != nil {
			arg1 = args[1].(studyguides.RemoveVoteParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStudyGuideService_RemoveVote_Call) Return(err error) *MockStudyGuideService_RemoveVote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStudyGuideService_RemoveVote_Call) RunAndReturn(run func(ctx context.Context, params studyguides.RemoveVoteParams) error) *MockStudyGuideService_RemoveVote_Call {
	_c.Call.Return(run)
	return _c
}
