from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.create_file_request_mime_type import CreateFileRequestMimeType

T = TypeVar("T", bound="CreateFileRequest")


@_attrs_define
class CreateFileRequest:
    """Payload to create a new file metadata record (ASK-105).
    Caller (typically the Next.js server) generates the S3 key
    and provides it here; the Go API never touches S3 for
    uploads. The record is created in `pending` status; a
    subsequent PATCH transitions it to `complete` or `failed`.

        Attributes:
            name (str):
            mime_type (CreateFileRequestMimeType):
            size (int):
            s3_key (str): S3 object key generated by the caller. Stored as-is on
                the file record; the Go API does not validate this
                against S3.
    """

    name: str
    mime_type: CreateFileRequestMimeType
    size: int
    s3_key: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        mime_type = self.mime_type.value

        size = self.size

        s3_key = self.s3_key

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "name": name,
                "mime_type": mime_type,
                "size": size,
                "s3_key": s3_key,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        mime_type = CreateFileRequestMimeType(d.pop("mime_type"))

        size = d.pop("size")

        s3_key = d.pop("s3_key")

        create_file_request = cls(
            name=name,
            mime_type=mime_type,
            size=size,
            s3_key=s3_key,
        )

        create_file_request.additional_properties = d
        return create_file_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
