import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/askatlas-api",
    },
    {
      type: "category",
      label: "UNTAGGED",
      items: [
        {
          type: "doc",
          id: "api/list-files",
          label: "List files for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-file",
          label: "Create a file metadata record (ASK-105)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-file",
          label: "Get a file by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-file",
          label: "Update file metadata and status (ASK-113)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-file",
          label: "Delete a file by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/record-file-view",
          label: "Record a file view (ASK-134)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/toggle-file-favorite",
          label: "Toggle the file favorite (ASK-130)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/toggle-study-guide-favorite",
          label: "Toggle the study guide favorite (ASK-156)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/toggle-course-favorite",
          label: "Toggle the course favorite (ASK-157)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/create-grant",
          label: "Grant a permission on a file (ASK-122)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/revoke-grant",
          label: "Revoke a permission on a file (ASK-125)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-schools",
          label: "List and search schools",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-school",
          label: "Get a single school by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-courses",
          label: "List and search courses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-course",
          label: "Get a course detail with embedded sections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-study-guide",
          label: "Get a study guide detail",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-study-guide",
          label: "Update a study guide",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-study-guide",
          label: "Soft-delete a study guide",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/attach-resource",
          label: "Attach an external resource to a study guide",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/detach-resource",
          label: "Detach a resource from a study guide",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/attach-file",
          label: "Attach a file to a study guide",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/detach-file",
          label: "Detach a file from a study guide",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-quizzes",
          label: "List quizzes attached to a study guide",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-quiz",
          label: "Create a quiz attached to a study guide",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-quiz",
          label: "Get a quiz with all questions and correct answers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-quiz",
          label: "Update a quiz's metadata (title and/or description)",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/delete-quiz",
          label: "Soft-delete a quiz",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/add-quiz-question",
          label: "Add a question to an existing quiz",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-practice-sessions",
          label: "List the authenticated user's practice sessions for a quiz",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/start-practice-session",
          label: "Start a new practice session or resume an existing incomplete one",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-practice-session",
          label: "Get a practice session detail including all submitted answers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/abandon-practice-session",
          label: "Hard-delete an in-progress practice session",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/complete-practice-session",
          label: "Mark a practice session as completed and return the score",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/submit-practice-answer",
          label: "Submit an answer for one question in a practice session",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/recommend-study-guide",
          label: "Recommend a study guide",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-study-guide-recommendation",
          label: "Remove the authenticated user's recommendation on a study guide",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/cast-study-guide-vote",
          label: "Cast or change a vote on a study guide",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/remove-study-guide-vote",
          label: "Remove the authenticated user's vote on a study guide",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-study-guides",
          label: "List study guides for a course",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-study-guide",
          label: "Create a study guide for a course",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-course-sections",
          label: "List sections for a course",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-section-members",
          label: "List the members of a course section",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/join-section",
          label: "Join a section as the authenticated user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-my-enrollments",
          label: "List the authenticated user's section enrollments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-dashboard",
          label: "Aggregated dashboard data for the authenticated user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-favorites",
          label: "List the authenticated user's favorited items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-recents",
          label: "List the authenticated user's most recently viewed items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/check-membership",
          label: "Check the authenticated user's membership in a section",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/leave-section",
          label: "Leave a section as the authenticated user",
          className: "api-method delete",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
