// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_recents

import (
	"context"

	"github.com/Ask-Atlas/AskAtlas/api/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ListRecentCourses provides a mock function for the type MockRepository
func (_mock *MockRepository) ListRecentCourses(ctx context.Context, arg db.ListRecentCoursesParams) ([]db.ListRecentCoursesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentCourses")
	}

	var r0 []db.ListRecentCoursesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentCoursesParams) ([]db.ListRecentCoursesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentCoursesParams) []db.ListRecentCoursesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListRecentCoursesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListRecentCoursesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListRecentCourses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentCourses'
type MockRepository_ListRecentCourses_Call struct {
	*mock.Call
}

// ListRecentCourses is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListRecentCoursesParams
func (_e *MockRepository_Expecter) ListRecentCourses(ctx interface{}, arg interface{}) *MockRepository_ListRecentCourses_Call {
	return &MockRepository_ListRecentCourses_Call{Call: _e.mock.On("ListRecentCourses", ctx, arg)}
}

func (_c *MockRepository_ListRecentCourses_Call) Run(run func(ctx context.Context, arg db.ListRecentCoursesParams)) *MockRepository_ListRecentCourses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListRecentCoursesParams
		if args[1] != nil {
			arg1 = args[1].(db.ListRecentCoursesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListRecentCourses_Call) Return(listRecentCoursesRows []db.ListRecentCoursesRow, err error) *MockRepository_ListRecentCourses_Call {
	_c.Call.Return(listRecentCoursesRows, err)
	return _c
}

func (_c *MockRepository_ListRecentCourses_Call) RunAndReturn(run func(ctx context.Context, arg db.ListRecentCoursesParams) ([]db.ListRecentCoursesRow, error)) *MockRepository_ListRecentCourses_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentFiles provides a mock function for the type MockRepository
func (_mock *MockRepository) ListRecentFiles(ctx context.Context, arg db.ListRecentFilesParams) ([]db.ListRecentFilesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentFiles")
	}

	var r0 []db.ListRecentFilesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentFilesParams) ([]db.ListRecentFilesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentFilesParams) []db.ListRecentFilesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListRecentFilesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListRecentFilesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListRecentFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentFiles'
type MockRepository_ListRecentFiles_Call struct {
	*mock.Call
}

// ListRecentFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListRecentFilesParams
func (_e *MockRepository_Expecter) ListRecentFiles(ctx interface{}, arg interface{}) *MockRepository_ListRecentFiles_Call {
	return &MockRepository_ListRecentFiles_Call{Call: _e.mock.On("ListRecentFiles", ctx, arg)}
}

func (_c *MockRepository_ListRecentFiles_Call) Run(run func(ctx context.Context, arg db.ListRecentFilesParams)) *MockRepository_ListRecentFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListRecentFilesParams
		if args[1] != nil {
			arg1 = args[1].(db.ListRecentFilesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListRecentFiles_Call) Return(listRecentFilesRows []db.ListRecentFilesRow, err error) *MockRepository_ListRecentFiles_Call {
	_c.Call.Return(listRecentFilesRows, err)
	return _c
}

func (_c *MockRepository_ListRecentFiles_Call) RunAndReturn(run func(ctx context.Context, arg db.ListRecentFilesParams) ([]db.ListRecentFilesRow, error)) *MockRepository_ListRecentFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentStudyGuides provides a mock function for the type MockRepository
func (_mock *MockRepository) ListRecentStudyGuides(ctx context.Context, arg db.ListRecentStudyGuidesParams) ([]db.ListRecentStudyGuidesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentStudyGuides")
	}

	var r0 []db.ListRecentStudyGuidesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentStudyGuidesParams) ([]db.ListRecentStudyGuidesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.ListRecentStudyGuidesParams) []db.ListRecentStudyGuidesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListRecentStudyGuidesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.ListRecentStudyGuidesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListRecentStudyGuides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentStudyGuides'
type MockRepository_ListRecentStudyGuides_Call struct {
	*mock.Call
}

// ListRecentStudyGuides is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.ListRecentStudyGuidesParams
func (_e *MockRepository_Expecter) ListRecentStudyGuides(ctx interface{}, arg interface{}) *MockRepository_ListRecentStudyGuides_Call {
	return &MockRepository_ListRecentStudyGuides_Call{Call: _e.mock.On("ListRecentStudyGuides", ctx, arg)}
}

func (_c *MockRepository_ListRecentStudyGuides_Call) Run(run func(ctx context.Context, arg db.ListRecentStudyGuidesParams)) *MockRepository_ListRecentStudyGuides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.ListRecentStudyGuidesParams
		if args[1] != nil {
			arg1 = args[1].(db.ListRecentStudyGuidesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListRecentStudyGuides_Call) Return(listRecentStudyGuidesRows []db.ListRecentStudyGuidesRow, err error) *MockRepository_ListRecentStudyGuides_Call {
	_c.Call.Return(listRecentStudyGuidesRows, err)
	return _c
}

func (_c *MockRepository_ListRecentStudyGuides_Call) RunAndReturn(run func(ctx context.Context, arg db.ListRecentStudyGuidesParams) ([]db.ListRecentStudyGuidesRow, error)) *MockRepository_ListRecentStudyGuides_Call {
	_c.Call.Return(run)
	return _c
}
