// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_quizzes

import (
	"context"

	"github.com/Ask-Atlas/AskAtlas/api/internal/db"
	"github.com/Ask-Atlas/AskAtlas/api/internal/quizzes"
	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetQuizByIDForUpdate provides a mock function for the type MockRepository
func (_mock *MockRepository) GetQuizByIDForUpdate(ctx context.Context, id pgtype.UUID) (db.GetQuizByIDForUpdateRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuizByIDForUpdate")
	}

	var r0 db.GetQuizByIDForUpdateRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.GetQuizByIDForUpdateRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.GetQuizByIDForUpdateRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetQuizByIDForUpdateRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetQuizByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuizByIDForUpdate'
type MockRepository_GetQuizByIDForUpdate_Call struct {
	*mock.Call
}

// GetQuizByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) GetQuizByIDForUpdate(ctx interface{}, id interface{}) *MockRepository_GetQuizByIDForUpdate_Call {
	return &MockRepository_GetQuizByIDForUpdate_Call{Call: _e.mock.On("GetQuizByIDForUpdate", ctx, id)}
}

func (_c *MockRepository_GetQuizByIDForUpdate_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_GetQuizByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetQuizByIDForUpdate_Call) Return(getQuizByIDForUpdateRow db.GetQuizByIDForUpdateRow, err error) *MockRepository_GetQuizByIDForUpdate_Call {
	_c.Call.Return(getQuizByIDForUpdateRow, err)
	return _c
}

func (_c *MockRepository_GetQuizByIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (db.GetQuizByIDForUpdateRow, error)) *MockRepository_GetQuizByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuizDetail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetQuizDetail(ctx context.Context, id pgtype.UUID) (db.GetQuizDetailRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuizDetail")
	}

	var r0 db.GetQuizDetailRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.GetQuizDetailRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.GetQuizDetailRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetQuizDetailRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetQuizDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuizDetail'
type MockRepository_GetQuizDetail_Call struct {
	*mock.Call
}

// GetQuizDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) GetQuizDetail(ctx interface{}, id interface{}) *MockRepository_GetQuizDetail_Call {
	return &MockRepository_GetQuizDetail_Call{Call: _e.mock.On("GetQuizDetail", ctx, id)}
}

func (_c *MockRepository_GetQuizDetail_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_GetQuizDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetQuizDetail_Call) Return(getQuizDetailRow db.GetQuizDetailRow, err error) *MockRepository_GetQuizDetail_Call {
	_c.Call.Return(getQuizDetailRow, err)
	return _c
}

func (_c *MockRepository_GetQuizDetail_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (db.GetQuizDetailRow, error)) *MockRepository_GetQuizDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuizForUpdateWithParentStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) GetQuizForUpdateWithParentStatus(ctx context.Context, id pgtype.UUID) (db.GetQuizForUpdateWithParentStatusRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuizForUpdateWithParentStatus")
	}

	var r0 db.GetQuizForUpdateWithParentStatusRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (db.GetQuizForUpdateWithParentStatusRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) db.GetQuizForUpdateWithParentStatusRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetQuizForUpdateWithParentStatusRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetQuizForUpdateWithParentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuizForUpdateWithParentStatus'
type MockRepository_GetQuizForUpdateWithParentStatus_Call struct {
	*mock.Call
}

// GetQuizForUpdateWithParentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) GetQuizForUpdateWithParentStatus(ctx interface{}, id interface{}) *MockRepository_GetQuizForUpdateWithParentStatus_Call {
	return &MockRepository_GetQuizForUpdateWithParentStatus_Call{Call: _e.mock.On("GetQuizForUpdateWithParentStatus", ctx, id)}
}

func (_c *MockRepository_GetQuizForUpdateWithParentStatus_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_GetQuizForUpdateWithParentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetQuizForUpdateWithParentStatus_Call) Return(getQuizForUpdateWithParentStatusRow db.GetQuizForUpdateWithParentStatusRow, err error) *MockRepository_GetQuizForUpdateWithParentStatus_Call {
	_c.Call.Return(getQuizForUpdateWithParentStatusRow, err)
	return _c
}

func (_c *MockRepository_GetQuizForUpdateWithParentStatus_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (db.GetQuizForUpdateWithParentStatusRow, error)) *MockRepository_GetQuizForUpdateWithParentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GuideExistsAndLiveForQuizzes provides a mock function for the type MockRepository
func (_mock *MockRepository) GuideExistsAndLiveForQuizzes(ctx context.Context, id pgtype.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GuideExistsAndLiveForQuizzes")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GuideExistsAndLiveForQuizzes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuideExistsAndLiveForQuizzes'
type MockRepository_GuideExistsAndLiveForQuizzes_Call struct {
	*mock.Call
}

// GuideExistsAndLiveForQuizzes is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) GuideExistsAndLiveForQuizzes(ctx interface{}, id interface{}) *MockRepository_GuideExistsAndLiveForQuizzes_Call {
	return &MockRepository_GuideExistsAndLiveForQuizzes_Call{Call: _e.mock.On("GuideExistsAndLiveForQuizzes", ctx, id)}
}

func (_c *MockRepository_GuideExistsAndLiveForQuizzes_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_GuideExistsAndLiveForQuizzes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GuideExistsAndLiveForQuizzes_Call) Return(b bool, err error) *MockRepository_GuideExistsAndLiveForQuizzes_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_GuideExistsAndLiveForQuizzes_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (bool, error)) *MockRepository_GuideExistsAndLiveForQuizzes_Call {
	_c.Call.Return(run)
	return _c
}

// InTx provides a mock function for the type MockRepository
func (_mock *MockRepository) InTx(ctx context.Context, fn func(quizzes.Repository) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for InTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(quizzes.Repository) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InTx'
type MockRepository_InTx_Call struct {
	*mock.Call
}

// InTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(quizzes.Repository) error
func (_e *MockRepository_Expecter) InTx(ctx interface{}, fn interface{}) *MockRepository_InTx_Call {
	return &MockRepository_InTx_Call{Call: _e.mock.On("InTx", ctx, fn)}
}

func (_c *MockRepository_InTx_Call) Run(run func(ctx context.Context, fn func(quizzes.Repository) error)) *MockRepository_InTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(quizzes.Repository) error
		if args[1] != nil {
			arg1 = args[1].(func(quizzes.Repository) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InTx_Call) Return(err error) *MockRepository_InTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InTx_Call) RunAndReturn(run func(ctx context.Context, fn func(quizzes.Repository) error) error) *MockRepository_InTx_Call {
	_c.Call.Return(run)
	return _c
}

// InsertQuiz provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertQuiz(ctx context.Context, arg db.InsertQuizParams) (db.InsertQuizRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertQuiz")
	}

	var r0 db.InsertQuizRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.InsertQuizParams) (db.InsertQuizRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.InsertQuizParams) db.InsertQuizRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.InsertQuizRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.InsertQuizParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_InsertQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertQuiz'
type MockRepository_InsertQuiz_Call struct {
	*mock.Call
}

// InsertQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertQuizParams
func (_e *MockRepository_Expecter) InsertQuiz(ctx interface{}, arg interface{}) *MockRepository_InsertQuiz_Call {
	return &MockRepository_InsertQuiz_Call{Call: _e.mock.On("InsertQuiz", ctx, arg)}
}

func (_c *MockRepository_InsertQuiz_Call) Run(run func(ctx context.Context, arg db.InsertQuizParams)) *MockRepository_InsertQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.InsertQuizParams
		if args[1] != nil {
			arg1 = args[1].(db.InsertQuizParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertQuiz_Call) Return(insertQuizRow db.InsertQuizRow, err error) *MockRepository_InsertQuiz_Call {
	_c.Call.Return(insertQuizRow, err)
	return _c
}

func (_c *MockRepository_InsertQuiz_Call) RunAndReturn(run func(ctx context.Context, arg db.InsertQuizParams) (db.InsertQuizRow, error)) *MockRepository_InsertQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// InsertQuizAnswerOption provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertQuizAnswerOption(ctx context.Context, arg db.InsertQuizAnswerOptionParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertQuizAnswerOption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.InsertQuizAnswerOptionParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertQuizAnswerOption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertQuizAnswerOption'
type MockRepository_InsertQuizAnswerOption_Call struct {
	*mock.Call
}

// InsertQuizAnswerOption is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertQuizAnswerOptionParams
func (_e *MockRepository_Expecter) InsertQuizAnswerOption(ctx interface{}, arg interface{}) *MockRepository_InsertQuizAnswerOption_Call {
	return &MockRepository_InsertQuizAnswerOption_Call{Call: _e.mock.On("InsertQuizAnswerOption", ctx, arg)}
}

func (_c *MockRepository_InsertQuizAnswerOption_Call) Run(run func(ctx context.Context, arg db.InsertQuizAnswerOptionParams)) *MockRepository_InsertQuizAnswerOption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.InsertQuizAnswerOptionParams
		if args[1] != nil {
			arg1 = args[1].(db.InsertQuizAnswerOptionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertQuizAnswerOption_Call) Return(err error) *MockRepository_InsertQuizAnswerOption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertQuizAnswerOption_Call) RunAndReturn(run func(ctx context.Context, arg db.InsertQuizAnswerOptionParams) error) *MockRepository_InsertQuizAnswerOption_Call {
	_c.Call.Return(run)
	return _c
}

// InsertQuizQuestion provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertQuizQuestion(ctx context.Context, arg db.InsertQuizQuestionParams) (pgtype.UUID, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertQuizQuestion")
	}

	var r0 pgtype.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.InsertQuizQuestionParams) (pgtype.UUID, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.InsertQuizQuestionParams) pgtype.UUID); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(pgtype.UUID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.InsertQuizQuestionParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_InsertQuizQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertQuizQuestion'
type MockRepository_InsertQuizQuestion_Call struct {
	*mock.Call
}

// InsertQuizQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertQuizQuestionParams
func (_e *MockRepository_Expecter) InsertQuizQuestion(ctx interface{}, arg interface{}) *MockRepository_InsertQuizQuestion_Call {
	return &MockRepository_InsertQuizQuestion_Call{Call: _e.mock.On("InsertQuizQuestion", ctx, arg)}
}

func (_c *MockRepository_InsertQuizQuestion_Call) Run(run func(ctx context.Context, arg db.InsertQuizQuestionParams)) *MockRepository_InsertQuizQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.InsertQuizQuestionParams
		if args[1] != nil {
			arg1 = args[1].(db.InsertQuizQuestionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertQuizQuestion_Call) Return(uUID pgtype.UUID, err error) *MockRepository_InsertQuizQuestion_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRepository_InsertQuizQuestion_Call) RunAndReturn(run func(ctx context.Context, arg db.InsertQuizQuestionParams) (pgtype.UUID, error)) *MockRepository_InsertQuizQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuizAnswerOptionsByQuiz provides a mock function for the type MockRepository
func (_mock *MockRepository) ListQuizAnswerOptionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]db.QuizAnswerOption, error) {
	ret := _mock.Called(ctx, quizID)

	if len(ret) == 0 {
		panic("no return value specified for ListQuizAnswerOptionsByQuiz")
	}

	var r0 []db.QuizAnswerOption
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.QuizAnswerOption, error)); ok {
		return returnFunc(ctx, quizID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.QuizAnswerOption); ok {
		r0 = returnFunc(ctx, quizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.QuizAnswerOption)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, quizID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListQuizAnswerOptionsByQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuizAnswerOptionsByQuiz'
type MockRepository_ListQuizAnswerOptionsByQuiz_Call struct {
	*mock.Call
}

// ListQuizAnswerOptionsByQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - quizID pgtype.UUID
func (_e *MockRepository_Expecter) ListQuizAnswerOptionsByQuiz(ctx interface{}, quizID interface{}) *MockRepository_ListQuizAnswerOptionsByQuiz_Call {
	return &MockRepository_ListQuizAnswerOptionsByQuiz_Call{Call: _e.mock.On("ListQuizAnswerOptionsByQuiz", ctx, quizID)}
}

func (_c *MockRepository_ListQuizAnswerOptionsByQuiz_Call) Run(run func(ctx context.Context, quizID pgtype.UUID)) *MockRepository_ListQuizAnswerOptionsByQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListQuizAnswerOptionsByQuiz_Call) Return(quizAnswerOptions []db.QuizAnswerOption, err error) *MockRepository_ListQuizAnswerOptionsByQuiz_Call {
	_c.Call.Return(quizAnswerOptions, err)
	return _c
}

func (_c *MockRepository_ListQuizAnswerOptionsByQuiz_Call) RunAndReturn(run func(ctx context.Context, quizID pgtype.UUID) ([]db.QuizAnswerOption, error)) *MockRepository_ListQuizAnswerOptionsByQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuizQuestionsByQuiz provides a mock function for the type MockRepository
func (_mock *MockRepository) ListQuizQuestionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]db.ListQuizQuestionsByQuizRow, error) {
	ret := _mock.Called(ctx, quizID)

	if len(ret) == 0 {
		panic("no return value specified for ListQuizQuestionsByQuiz")
	}

	var r0 []db.ListQuizQuestionsByQuizRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ListQuizQuestionsByQuizRow, error)); ok {
		return returnFunc(ctx, quizID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ListQuizQuestionsByQuizRow); ok {
		r0 = returnFunc(ctx, quizID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListQuizQuestionsByQuizRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, quizID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListQuizQuestionsByQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuizQuestionsByQuiz'
type MockRepository_ListQuizQuestionsByQuiz_Call struct {
	*mock.Call
}

// ListQuizQuestionsByQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - quizID pgtype.UUID
func (_e *MockRepository_Expecter) ListQuizQuestionsByQuiz(ctx interface{}, quizID interface{}) *MockRepository_ListQuizQuestionsByQuiz_Call {
	return &MockRepository_ListQuizQuestionsByQuiz_Call{Call: _e.mock.On("ListQuizQuestionsByQuiz", ctx, quizID)}
}

func (_c *MockRepository_ListQuizQuestionsByQuiz_Call) Run(run func(ctx context.Context, quizID pgtype.UUID)) *MockRepository_ListQuizQuestionsByQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListQuizQuestionsByQuiz_Call) Return(listQuizQuestionsByQuizRows []db.ListQuizQuestionsByQuizRow, err error) *MockRepository_ListQuizQuestionsByQuiz_Call {
	_c.Call.Return(listQuizQuestionsByQuizRows, err)
	return _c
}

func (_c *MockRepository_ListQuizQuestionsByQuiz_Call) RunAndReturn(run func(ctx context.Context, quizID pgtype.UUID) ([]db.ListQuizQuestionsByQuizRow, error)) *MockRepository_ListQuizQuestionsByQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// ListQuizzesByStudyGuide provides a mock function for the type MockRepository
func (_mock *MockRepository) ListQuizzesByStudyGuide(ctx context.Context, studyGuideID pgtype.UUID) ([]db.ListQuizzesByStudyGuideRow, error) {
	ret := _mock.Called(ctx, studyGuideID)

	if len(ret) == 0 {
		panic("no return value specified for ListQuizzesByStudyGuide")
	}

	var r0 []db.ListQuizzesByStudyGuideRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ListQuizzesByStudyGuideRow, error)); ok {
		return returnFunc(ctx, studyGuideID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ListQuizzesByStudyGuideRow); ok {
		r0 = returnFunc(ctx, studyGuideID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ListQuizzesByStudyGuideRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, studyGuideID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListQuizzesByStudyGuide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQuizzesByStudyGuide'
type MockRepository_ListQuizzesByStudyGuide_Call struct {
	*mock.Call
}

// ListQuizzesByStudyGuide is a helper method to define mock.On call
//   - ctx context.Context
//   - studyGuideID pgtype.UUID
func (_e *MockRepository_Expecter) ListQuizzesByStudyGuide(ctx interface{}, studyGuideID interface{}) *MockRepository_ListQuizzesByStudyGuide_Call {
	return &MockRepository_ListQuizzesByStudyGuide_Call{Call: _e.mock.On("ListQuizzesByStudyGuide", ctx, studyGuideID)}
}

func (_c *MockRepository_ListQuizzesByStudyGuide_Call) Run(run func(ctx context.Context, studyGuideID pgtype.UUID)) *MockRepository_ListQuizzesByStudyGuide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListQuizzesByStudyGuide_Call) Return(listQuizzesByStudyGuideRows []db.ListQuizzesByStudyGuideRow, err error) *MockRepository_ListQuizzesByStudyGuide_Call {
	_c.Call.Return(listQuizzesByStudyGuideRows, err)
	return _c
}

func (_c *MockRepository_ListQuizzesByStudyGuide_Call) RunAndReturn(run func(ctx context.Context, studyGuideID pgtype.UUID) ([]db.ListQuizzesByStudyGuideRow, error)) *MockRepository_ListQuizzesByStudyGuide_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDeleteQuiz provides a mock function for the type MockRepository
func (_mock *MockRepository) SoftDeleteQuiz(ctx context.Context, id pgtype.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteQuiz")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SoftDeleteQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDeleteQuiz'
type MockRepository_SoftDeleteQuiz_Call struct {
	*mock.Call
}

// SoftDeleteQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockRepository_Expecter) SoftDeleteQuiz(ctx interface{}, id interface{}) *MockRepository_SoftDeleteQuiz_Call {
	return &MockRepository_SoftDeleteQuiz_Call{Call: _e.mock.On("SoftDeleteQuiz", ctx, id)}
}

func (_c *MockRepository_SoftDeleteQuiz_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockRepository_SoftDeleteQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SoftDeleteQuiz_Call) Return(err error) *MockRepository_SoftDeleteQuiz_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SoftDeleteQuiz_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) error) *MockRepository_SoftDeleteQuiz_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuiz provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateQuiz(ctx context.Context, arg db.UpdateQuizParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuiz")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateQuizParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateQuiz_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuiz'
type MockRepository_UpdateQuiz_Call struct {
	*mock.Call
}

// UpdateQuiz is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateQuizParams
func (_e *MockRepository_Expecter) UpdateQuiz(ctx interface{}, arg interface{}) *MockRepository_UpdateQuiz_Call {
	return &MockRepository_UpdateQuiz_Call{Call: _e.mock.On("UpdateQuiz", ctx, arg)}
}

func (_c *MockRepository_UpdateQuiz_Call) Run(run func(ctx context.Context, arg db.UpdateQuizParams)) *MockRepository_UpdateQuiz_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateQuizParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateQuizParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateQuiz_Call) Return(err error) *MockRepository_UpdateQuiz_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateQuiz_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateQuizParams) error) *MockRepository_UpdateQuiz_Call {
	_c.Call.Return(run)
	return _c
}
