// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_files

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockS3Downloader creates a new instance of MockS3Downloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Downloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Downloader {
	mock := &MockS3Downloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3Downloader is an autogenerated mock type for the S3Downloader type
type MockS3Downloader struct {
	mock.Mock
}

type MockS3Downloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Downloader) EXPECT() *MockS3Downloader_Expecter {
	return &MockS3Downloader_Expecter{mock: &_m.Mock}
}

// GetObject provides a mock function for the type MockS3Downloader
func (_mock *MockS3Downloader) GetObject(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3Downloader_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockS3Downloader_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockS3Downloader_Expecter) GetObject(ctx interface{}, key interface{}) *MockS3Downloader_GetObject_Call {
	return &MockS3Downloader_GetObject_Call{Call: _e.mock.On("GetObject", ctx, key)}
}

func (_c *MockS3Downloader_GetObject_Call) Run(run func(ctx context.Context, key string)) *MockS3Downloader_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3Downloader_GetObject_Call) Return(bytes []byte, err error) *MockS3Downloader_GetObject_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockS3Downloader_GetObject_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockS3Downloader_GetObject_Call {
	_c.Call.Return(run)
	return _c
}
