// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseExists = `-- name: CourseExists :one
SELECT EXISTS (
  SELECT 1 FROM courses WHERE id = $1::uuid
) AS exists
`

// Single-row existence probe used by join/leave to disambiguate the
// "Course not found" 404 from the "Section not found" 404 the spec
// requires (see ASK-132 / ASK-138).
func (q *Queries) CourseExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, courseExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCourse = `-- name: GetCourse :one
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE c.id = $1::uuid
`

type GetCourseRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) GetCourse(ctx context.Context, id pgtype.UUID) (GetCourseRow, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i GetCourseRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Department,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SID,
		&i.SName,
		&i.SAcronym,
		&i.SCity,
		&i.SState,
		&i.SCountry,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT role, joined_at
FROM course_members
WHERE user_id = $1::uuid
  AND section_id = $2::uuid
`

type GetMembershipParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

type GetMembershipRow struct {
	Role     CourseRole         `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

// Single-row membership lookup powering the per-section
// enrolled/not-enrolled probe (ASK-148). Returns sql.ErrNoRows when the
// viewer is not a member; the service translates that into the 200
// {enrolled:false} response, NOT a 404.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.SectionID)
	var i GetMembershipRow
	err := row.Scan(&i.Role, &i.JoinedAt)
	return i, err
}

const joinSection = `-- name: JoinSection :one
INSERT INTO course_members (user_id, section_id, role)
VALUES ($1::uuid, $2::uuid, 'student')
ON CONFLICT (user_id, section_id) DO NOTHING
RETURNING user_id, section_id, role, joined_at
`

type JoinSectionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

// Adds the user to the section as a 'student'. ON CONFLICT DO NOTHING
// keeps duplicate joins atomic (no PK violation surfacing) and concurrency
// safe; the service layer treats an empty result as the 409 "Already a
// member of this section" case.
func (q *Queries) JoinSection(ctx context.Context, arg JoinSectionParams) (CourseMember, error) {
	row := q.db.QueryRow(ctx, joinSection, arg.UserID, arg.SectionID)
	var i CourseMember
	err := row.Scan(
		&i.UserID,
		&i.SectionID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const leaveSection = `-- name: LeaveSection :one
DELETE FROM course_members
WHERE user_id = $1::uuid
  AND section_id = $2::uuid
RETURNING user_id
`

type LeaveSectionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	SectionID pgtype.UUID `json:"section_id"`
}

// Hard-deletes the membership row. RETURNING lets the service detect a
// no-op delete (sql.ErrNoRows) and map it to the 404 "Not a member of
// this section" response.
func (q *Queries) LeaveSection(ctx context.Context, arg LeaveSectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, leaveSection, arg.UserID, arg.SectionID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listCourseSections = `-- name: ListCourseSections :many
SELECT
  cs.id, cs.term, cs.section_code, cs.instructor_name, cs.start_date,
  COUNT(cm.user_id) AS member_count
FROM course_sections cs
LEFT JOIN course_members cm ON cm.section_id = cs.id
WHERE cs.course_id = $1::uuid
GROUP BY cs.id
ORDER BY cs.start_date DESC NULLS LAST, cs.section_code ASC NULLS LAST, cs.id ASC
`

type ListCourseSectionsRow struct {
	ID             pgtype.UUID `json:"id"`
	Term           string      `json:"term"`
	SectionCode    pgtype.Text `json:"section_code"`
	InstructorName pgtype.Text `json:"instructor_name"`
	StartDate      pgtype.Date `json:"start_date"`
	MemberCount    int64       `json:"member_count"`
}

// Returns sections with a live member_count via LEFT JOIN (so sections
// with zero members still appear). Ordered most-recent term first using
// start_date when present, falling back to section_code. NULLS LAST keeps
// sections without a known start_date at the bottom.
func (q *Queries) ListCourseSections(ctx context.Context, courseID pgtype.UUID) ([]ListCourseSectionsRow, error) {
	rows, err := q.db.Query(ctx, listCourseSections, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseSectionsRow
	for rows.Next() {
		var i ListCourseSectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.SectionCode,
			&i.InstructorName,
			&i.StartDate,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesCreatedAtAsc = `-- name: ListCoursesCreatedAtAsc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::timestamptz IS NULL
    OR (c.created_at, c.id) > ($4::timestamptz, $5::uuid)
  )
ORDER BY c.created_at ASC, c.id ASC
LIMIT $6
`

type ListCoursesCreatedAtAscParams struct {
	SchoolID        pgtype.UUID        `json:"school_id"`
	Department      pgtype.Text        `json:"department"`
	Q               pgtype.Text        `json:"q"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCoursesCreatedAtAscRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesCreatedAtAsc(ctx context.Context, arg ListCoursesCreatedAtAscParams) ([]ListCoursesCreatedAtAscRow, error) {
	rows, err := q.db.Query(ctx, listCoursesCreatedAtAsc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesCreatedAtAscRow
	for rows.Next() {
		var i ListCoursesCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesCreatedAtDesc = `-- name: ListCoursesCreatedAtDesc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::timestamptz IS NULL
    OR (c.created_at, c.id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY c.created_at DESC, c.id DESC
LIMIT $6
`

type ListCoursesCreatedAtDescParams struct {
	SchoolID        pgtype.UUID        `json:"school_id"`
	Department      pgtype.Text        `json:"department"`
	Q               pgtype.Text        `json:"q"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCoursesCreatedAtDescRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesCreatedAtDesc(ctx context.Context, arg ListCoursesCreatedAtDescParams) ([]ListCoursesCreatedAtDescRow, error) {
	rows, err := q.db.Query(ctx, listCoursesCreatedAtDesc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesCreatedAtDescRow
	for rows.Next() {
		var i ListCoursesCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesDepartmentAsc = `-- name: ListCoursesDepartmentAsc :many

SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.department, c.number, c.id) > (
      $4::text,
      $5::text,
      $6::uuid
    )
  )
ORDER BY c.department ASC, c.number ASC, c.id ASC
LIMIT $7
`

type ListCoursesDepartmentAscParams struct {
	SchoolID         pgtype.UUID `json:"school_id"`
	Department       pgtype.Text `json:"department"`
	Q                pgtype.Text `json:"q"`
	CursorDepartment pgtype.Text `json:"cursor_department"`
	CursorNumber     pgtype.Text `json:"cursor_number"`
	CursorID         pgtype.UUID `json:"cursor_id"`
	PageLimit        int32       `json:"page_limit"`
}

type ListCoursesDepartmentAscRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

// All ListCourses* variants share the same WHERE template
// (school_id, department, q filters + sort-specific cursor) and only
// differ in ORDER BY direction and the cursor field shape. This mirrors
// the per-sort-variant pattern in files.sql -- sqlc cannot parameterize
// ORDER BY, so each direction gets its own named query.
//
// The default sort (by department) uses a composite (department, number, id)
// cursor because (department) alone is not unique; the other sort fields
// use a simpler (field, id) cursor since the field is paired with the
// primary key as a tiebreaker.
func (q *Queries) ListCoursesDepartmentAsc(ctx context.Context, arg ListCoursesDepartmentAscParams) ([]ListCoursesDepartmentAscRow, error) {
	rows, err := q.db.Query(ctx, listCoursesDepartmentAsc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorDepartment,
		arg.CursorNumber,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesDepartmentAscRow
	for rows.Next() {
		var i ListCoursesDepartmentAscRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesDepartmentDesc = `-- name: ListCoursesDepartmentDesc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.department, c.number, c.id) < (
      $4::text,
      $5::text,
      $6::uuid
    )
  )
ORDER BY c.department DESC, c.number DESC, c.id DESC
LIMIT $7
`

type ListCoursesDepartmentDescParams struct {
	SchoolID         pgtype.UUID `json:"school_id"`
	Department       pgtype.Text `json:"department"`
	Q                pgtype.Text `json:"q"`
	CursorDepartment pgtype.Text `json:"cursor_department"`
	CursorNumber     pgtype.Text `json:"cursor_number"`
	CursorID         pgtype.UUID `json:"cursor_id"`
	PageLimit        int32       `json:"page_limit"`
}

type ListCoursesDepartmentDescRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesDepartmentDesc(ctx context.Context, arg ListCoursesDepartmentDescParams) ([]ListCoursesDepartmentDescRow, error) {
	rows, err := q.db.Query(ctx, listCoursesDepartmentDesc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorDepartment,
		arg.CursorNumber,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesDepartmentDescRow
	for rows.Next() {
		var i ListCoursesDepartmentDescRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesNumberAsc = `-- name: ListCoursesNumberAsc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.number, c.id) > ($4::text, $5::uuid)
  )
ORDER BY c.number ASC, c.id ASC
LIMIT $6
`

type ListCoursesNumberAscParams struct {
	SchoolID     pgtype.UUID `json:"school_id"`
	Department   pgtype.Text `json:"department"`
	Q            pgtype.Text `json:"q"`
	CursorNumber pgtype.Text `json:"cursor_number"`
	CursorID     pgtype.UUID `json:"cursor_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCoursesNumberAscRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesNumberAsc(ctx context.Context, arg ListCoursesNumberAscParams) ([]ListCoursesNumberAscRow, error) {
	rows, err := q.db.Query(ctx, listCoursesNumberAsc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorNumber,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesNumberAscRow
	for rows.Next() {
		var i ListCoursesNumberAscRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesNumberDesc = `-- name: ListCoursesNumberDesc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.number, c.id) < ($4::text, $5::uuid)
  )
ORDER BY c.number DESC, c.id DESC
LIMIT $6
`

type ListCoursesNumberDescParams struct {
	SchoolID     pgtype.UUID `json:"school_id"`
	Department   pgtype.Text `json:"department"`
	Q            pgtype.Text `json:"q"`
	CursorNumber pgtype.Text `json:"cursor_number"`
	CursorID     pgtype.UUID `json:"cursor_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListCoursesNumberDescRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesNumberDesc(ctx context.Context, arg ListCoursesNumberDescParams) ([]ListCoursesNumberDescRow, error) {
	rows, err := q.db.Query(ctx, listCoursesNumberDesc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorNumber,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesNumberDescRow
	for rows.Next() {
		var i ListCoursesNumberDescRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesTitleAsc = `-- name: ListCoursesTitleAsc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.title, c.id) > ($4::text, $5::uuid)
  )
ORDER BY c.title ASC, c.id ASC
LIMIT $6
`

type ListCoursesTitleAscParams struct {
	SchoolID    pgtype.UUID `json:"school_id"`
	Department  pgtype.Text `json:"department"`
	Q           pgtype.Text `json:"q"`
	CursorTitle pgtype.Text `json:"cursor_title"`
	CursorID    pgtype.UUID `json:"cursor_id"`
	PageLimit   int32       `json:"page_limit"`
}

type ListCoursesTitleAscRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesTitleAsc(ctx context.Context, arg ListCoursesTitleAscParams) ([]ListCoursesTitleAscRow, error) {
	rows, err := q.db.Query(ctx, listCoursesTitleAsc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorTitle,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesTitleAscRow
	for rows.Next() {
		var i ListCoursesTitleAscRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesTitleDesc = `-- name: ListCoursesTitleDesc :many
SELECT
  c.id, c.school_id, c.department, c.number, c.title, c.description,
  c.created_at, c.updated_at,
  s.id AS s_id, s.name AS s_name, s.acronym AS s_acronym,
  s.city AS s_city, s.state AS s_state, s.country AS s_country
FROM courses c
JOIN schools s ON s.id = c.school_id
WHERE
  ($1::uuid IS NULL OR c.school_id = $1::uuid)
  AND ($2::text IS NULL OR UPPER(c.department) = UPPER($2::text))
  AND (
    $3::text IS NULL
    OR c.title ILIKE '%' || $3::text || '%' ESCAPE '\'
    OR c.department ILIKE $3::text ESCAPE '\'
    OR c.number ILIKE $3::text ESCAPE '\'
  )
  AND (
    $4::text IS NULL
    OR (c.title, c.id) < ($4::text, $5::uuid)
  )
ORDER BY c.title DESC, c.id DESC
LIMIT $6
`

type ListCoursesTitleDescParams struct {
	SchoolID    pgtype.UUID `json:"school_id"`
	Department  pgtype.Text `json:"department"`
	Q           pgtype.Text `json:"q"`
	CursorTitle pgtype.Text `json:"cursor_title"`
	CursorID    pgtype.UUID `json:"cursor_id"`
	PageLimit   int32       `json:"page_limit"`
}

type ListCoursesTitleDescRow struct {
	ID          pgtype.UUID        `json:"id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	Department  string             `json:"department"`
	Number      string             `json:"number"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SID         pgtype.UUID        `json:"s_id"`
	SName       string             `json:"s_name"`
	SAcronym    string             `json:"s_acronym"`
	SCity       pgtype.Text        `json:"s_city"`
	SState      pgtype.Text        `json:"s_state"`
	SCountry    pgtype.Text        `json:"s_country"`
}

func (q *Queries) ListCoursesTitleDesc(ctx context.Context, arg ListCoursesTitleDescParams) ([]ListCoursesTitleDescRow, error) {
	rows, err := q.db.Query(ctx, listCoursesTitleDesc,
		arg.SchoolID,
		arg.Department,
		arg.Q,
		arg.CursorTitle,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoursesTitleDescRow
	for rows.Next() {
		var i ListCoursesTitleDescRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Department,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SID,
			&i.SName,
			&i.SAcronym,
			&i.SCity,
			&i.SState,
			&i.SCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEnrollments = `-- name: ListMyEnrollments :many
SELECT
  cs.id          AS section_id,
  cs.term        AS section_term,
  cs.section_code AS section_section_code,
  cs.instructor_name AS section_instructor_name,
  c.id           AS course_id,
  c.department   AS course_department,
  c.number       AS course_number,
  c.title        AS course_title,
  s.id           AS school_id,
  s.acronym      AS school_acronym,
  cm.role        AS member_role,
  cm.joined_at   AS member_joined_at
FROM course_members cm
JOIN course_sections cs ON cs.id = cm.section_id
JOIN courses c          ON c.id = cs.course_id
JOIN schools s          ON s.id = c.school_id
WHERE cm.user_id = $1::uuid
  AND ($2::text IS NULL OR cs.term = $2::text)
  AND ($3::course_role IS NULL OR cm.role = $3::course_role)
ORDER BY cs.term DESC, c.department ASC, c.number ASC
`

type ListMyEnrollmentsParams struct {
	UserID pgtype.UUID    `json:"user_id"`
	Term   pgtype.Text    `json:"term"`
	Role   NullCourseRole `json:"role"`
}

type ListMyEnrollmentsRow struct {
	SectionID             pgtype.UUID        `json:"section_id"`
	SectionTerm           string             `json:"section_term"`
	SectionSectionCode    pgtype.Text        `json:"section_section_code"`
	SectionInstructorName pgtype.Text        `json:"section_instructor_name"`
	CourseID              pgtype.UUID        `json:"course_id"`
	CourseDepartment      string             `json:"course_department"`
	CourseNumber          string             `json:"course_number"`
	CourseTitle           string             `json:"course_title"`
	SchoolID              pgtype.UUID        `json:"school_id"`
	SchoolAcronym         string             `json:"school_acronym"`
	MemberRole            CourseRole         `json:"member_role"`
	MemberJoinedAt        pgtype.Timestamptz `json:"member_joined_at"`
}

// Returns every section a user is enrolled in with the compact
// course + school payload the dashboard renders. Optional term + role
// filters use sqlc.narg so the WHERE branch short-circuits when
// they're absent. Sort is fixed: most-recent term first (lexicographic
// "Spring 2026" > "Fall 2025" is acceptable for MVP per the spec),
// then department + number for stable in-term ordering.
func (q *Queries) ListMyEnrollments(ctx context.Context, arg ListMyEnrollmentsParams) ([]ListMyEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listMyEnrollments, arg.UserID, arg.Term, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyEnrollmentsRow
	for rows.Next() {
		var i ListMyEnrollmentsRow
		if err := rows.Scan(
			&i.SectionID,
			&i.SectionTerm,
			&i.SectionSectionCode,
			&i.SectionInstructorName,
			&i.CourseID,
			&i.CourseDepartment,
			&i.CourseNumber,
			&i.CourseTitle,
			&i.SchoolID,
			&i.SchoolAcronym,
			&i.MemberRole,
			&i.MemberJoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sectionInCourseExists = `-- name: SectionInCourseExists :one
SELECT EXISTS (
  SELECT 1 FROM course_sections
  WHERE id = $1::uuid
    AND course_id = $2::uuid
) AS exists
`

type SectionInCourseExistsParams struct {
	SectionID pgtype.UUID `json:"section_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

// Verifies the section exists AND belongs to the supplied course. A
// section UUID that targets a different course is treated as not found
// to avoid leaking the existence of unrelated sections via the URL path.
func (q *Queries) SectionInCourseExists(ctx context.Context, arg SectionInCourseExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, sectionInCourseExists, arg.SectionID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
