// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	SoftDeleteUserByClerkID(ctx context.Context, clerkID string) (int64, error)
	UpsertClerkUser(ctx context.Context, arg UpsertClerkUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
