// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Returns TRUE when the question_id is part of this session's
	// frozen practice_session_questions snapshot. Used by ASK-137 to
	// enforce the spec's "question must be in this session's
	// snapshot" rule (400 otherwise -- the user can only answer
	// questions that were in the quiz at session-start time).
	CheckQuestionInSessionSnapshot(ctx context.Context, arg CheckQuestionInSessionSnapshotParams) (bool, error)
	// Practice session queries (ASK-128 start/resume).
	//
	// The StartPracticeSession service flow stitches these together:
	//   1. CheckQuizLiveForSession  -- 404 dispatch (quiz live + parent live)
	//   2. DeleteStaleIncompleteSessions -- hard-delete this user's
	//      incomplete session for this quiz if started_at > 7 days ago
	//   3. FindIncompleteSession -- if found, hydrate + return 200 (resume)
	//   4. CountQuizQuestions (reused from ASK-115) -- snapshot count
	//   5. Inside InTx:
	//        a. InsertPracticeSessionIfAbsent -- ON CONFLICT DO NOTHING
	//           backed by the partial unique index added in
	//           20260419083647_add_practice_sessions_partial_unique_index.
	//           Returns 0 rows on race -> service falls back to step 3.
	//        b. SnapshotQuizQuestions -- bulk insert practice_session_questions
	//           rows from quiz_questions
	//   6. ListSessionAnswers -- for the resume response (empty array on
	//      newly-created sessions because no answers exist yet)
	// Returns TRUE when both the quiz row AND its parent study guide are
	// live (deleted_at IS NULL on both). The service uses this as the
	// 404 gate before any writes -- a soft-deleted quiz, a quiz under a
	// soft-deleted guide, and a missing quiz all return FALSE here, which
	// the service maps to a single 404 response so the caller cannot
	// distinguish them (info-leak prevention).
	CheckQuizLiveForSession(ctx context.Context, quizID pgtype.UUID) (bool, error)
	// Recomputes the guide's vote_score from study_guide_votes. Returned
	// as int64 to match the wire shape on CastVoteResponse. Run after
	// the upsert in the same logical request so the response reflects the
	// post-mutation state.
	ComputeGuideVoteScore(ctx context.Context, studyGuideID pgtype.UUID) (int64, error)
	// Count of all questions on a quiz. Used by AddQuizQuestion (ASK-115)
	// to enforce the per-quiz 100-question cap inside the same
	// transaction as the insert, so two concurrent adds at the boundary
	// can't both squeeze through. Also doubles as the default
	// sort_order resolution (a new question lands at index = current
	// count when the caller doesn't supply an explicit value).
	CountQuizQuestions(ctx context.Context, quizID pgtype.UUID) (int64, error)
	// Single-row existence probe used by join/leave to disambiguate the
	// "Course not found" 404 from the "Section not found" 404 the spec
	// requires (see ASK-132 / ASK-138).
	CourseExists(ctx context.Context, id pgtype.UUID) (bool, error)
	// Single-row probe used by the list handler to disambiguate "course
	// missing" (404) from "course exists but has no guides" (200 empty
	// array). Separate from courses.CourseExists only because sqlc-generated
	// queriers are per-file; the predicate is identical.
	CourseExistsForGuides(ctx context.Context, id pgtype.UUID) (bool, error)
	// Removes the (file_id, study_guide_id) join row. Returns rows-
	// affected so the service can detect the concurrency-race case
	// (0 rows = a parallel detach already removed it, still maps to
	// 404 to match the get-then-delete contract). The file row is
	// preserved -- it may be attached to other guides + courses, and
	// the spec explicitly forbids cascading the file delete from a
	// single detach.
	DeleteGuideFile(ctx context.Context, arg DeleteGuideFileParams) (int64, error)
	// Removes the join row only. The resources row is preserved -- it
	// may be attached to other guides + courses, and the spec
	// explicitly forbids cascading the resource delete from a single
	// detach. Returns rows-affected so the service can detect
	// already-detached races (0 rows -> 404) vs success (1 row -> nil).
	DeleteGuideResource(ctx context.Context, arg DeleteGuideResourceParams) (int64, error)
	// Hard-deletes a practice session by id (ASK-144). The CASCADE
	// foreign keys on practice_session_questions and practice_answers
	// ensure the snapshot rows and answer rows are removed in the
	// same statement.
	//
	// Blind by id only -- the service has already verified ownership
	// + completed_at IS NULL inside the same tx via
	// LockSessionForCompletion + the FOR UPDATE row lock. By the
	// time this runs, the only legitimate outcome is "row deleted".
	// :execrows lets the service double-check the rows-affected
	// count (defense-in-depth) and surface a 500 on the
	// vanishingly-rare 0-rows path (would mean another tx slipped
	// in and deleted between our lock and this DELETE -- which is
	// ruled out by the FOR UPDATE row lock under READ COMMITTED,
	// but the check is cheap and self-documenting).
	DeleteSessionByID(ctx context.Context, id pgtype.UUID) (int64, error)
	// Hard-deletes this user's incomplete session for this quiz when it
	// has been sitting around longer than the caller-supplied stale
	// threshold. CASCADE deletes the attached practice_session_questions
	// and practice_answers rows.
	//
	// The threshold is a Go-side constant (sessions.StaleSessionAge,
	// currently 7 days) passed in as seconds so the policy lives in
	// exactly one place. Multiplying by `interval '1 second'` lets us
	// pass a plain integer instead of a Postgres interval value, which
	// keeps the sqlc-generated Go signature simple.
	//
	// Scoped per (user_id, quiz_id): we don't want a global cleanup job
	// here -- the spec wants stale-cleanup to run on the start-session
	// path so a user explicitly choosing to start fresh sees a clean
	// slate without waiting for a background job. Other users' stale
	// sessions on this same quiz are left alone (they'll be cleaned up
	// the next time THEY hit start-session).
	//
	// The partial unique index makes this idempotent -- at most one row
	// can match the WHERE clause, so DELETE is a no-op when there's no
	// stale session, and a single-row DELETE otherwise.
	DeleteStaleIncompleteSessions(ctx context.Context, arg DeleteStaleIncompleteSessionsParams) error
	// Hard-delete the (viewer, guide) recommendation row. Returns the
	// rows-affected count so the service can distinguish "viewer never
	// recommended this guide" (0 rows -> 404 'Recommendation not found')
	// from a successful delete (1 row -> 204). The guide-existence +
	// role gate runs FIRST in the service so 'Study guide not found' /
	// 403 win over 'Recommendation not found' when applicable.
	DeleteStudyGuideRecommendation(ctx context.Context, arg DeleteStudyGuideRecommendationParams) (int64, error)
	// Hard-delete the (viewer, guide) vote row (ASK-141). Returns the
	// rows-affected count so the service can distinguish "no existing
	// vote" (0 rows -> 404 'Vote not found') from a successful delete
	// (1 row -> 204). The guide-existence check happens BEFORE this
	// runs in the service so a missing guide doesn't leak through as
	// "vote not found".
	DeleteStudyGuideVote(ctx context.Context, arg DeleteStudyGuideVoteParams) (int64, error)
	// Resume probe -- returns this user's current in-progress session for
	// the quiz, if any. The partial unique index on
	// (user_id, quiz_id) WHERE completed_at IS NULL guarantees AT MOST
	// one row matches, so LIMIT 1 is belt-and-suspenders.
	//
	// Returns sql.ErrNoRows when no incomplete session exists; the
	// service treats that as the "create new" signal.
	FindIncompleteSession(ctx context.Context, arg FindIncompleteSessionParams) (FindIncompleteSessionRow, error)
	// Returns the text of the option marked is_correct for an MCQ or
	// TF question. Used by ASK-137 to compare against user_answer:
	//   * multiple-choice -- exact string equality with this text
	//   * true-false -- this text is "True" or "False" (the canonical
	//     labels written by the create-quiz path); the service maps
	//     it to a boolean and compares against the user's parsed
	//     "true"/"false" input.
	// Returns sql.ErrNoRows if no option is marked correct, which
	// the service treats as a data-integrity 500 (write-side
	// validation should have prevented it).
	GetCorrectOptionText(ctx context.Context, questionID pgtype.UUID) (string, error)
	GetCourse(ctx context.Context, id pgtype.UUID) (GetCourseRow, error)
	// Fetches a file only if it belongs to the given user and has not been soft-deleted.
	// Returns sql.ErrNoRows if not found or already in a deletion state.
	GetFileByOwner(ctx context.Context, arg GetFileByOwnerParams) (GetFileByOwnerRow, error)
	// File-side gate for AttachFile (ASK-121). Returns the file's
	// ownership + status fields so the service can choose 403 (not
	// owner) vs 404 (missing / not 'complete' / soft-deleted) without
	// a second round trip. Filters NOTHING -- the service inspects
	// status + deleted_at + deletion_status to decide vs returning
	// pre-filtered for "is the row attachable" since the messages
	// differ (403 vs 404) and we want to give the right one.
	//
	// The columns mirror files.GetFileByOwner -- this is intentional;
	// the cross-package read keeps the service layer aware of file
	// ownership without reaching into the files package.
	GetFileForAttach(ctx context.Context, id pgtype.UUID) (GetFileForAttachRow, error)
	GetFileIfViewable(ctx context.Context, arg GetFileIfViewableParams) (File, error)
	// Lookup for DetachResource (ASK-116). Returns the attached_by user
	// on the join row so the service can run the dual-authz check
	// (viewer is guide creator OR viewer is attached_by). sql.ErrNoRows
	// maps to 'Resource attachment not found' 404 -- the resource may
	// exist but isn't attached to THIS guide.
	GetGuideResourceAttacher(ctx context.Context, arg GetGuideResourceAttacherParams) (pgtype.UUID, error)
	// Single-row membership lookup powering the per-section
	// enrolled/not-enrolled probe (ASK-148). Returns sql.ErrNoRows when the
	// viewer is not a member; the service translates that into the 200
	// {enrolled:false} response, NOT a 404.
	GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error)
	// Locked SELECT used at the start of DeleteQuiz (ASK-102) and
	// UpdateQuiz (ASK-153). SELECT FOR UPDATE prevents two concurrent
	// mutators from racing on the same row -- one wins with 204/200,
	// the other sees the post-mutation state in its tx snapshot and
	// returns 404. Filters NOTHING -- the service inspects deleted_at
	// + creator_id to choose 404 vs 403 vs proceed (mirrors
	// studyguides.GetStudyGuideByIDForUpdate).
	GetQuizByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetQuizByIDForUpdateRow, error)
	// Load the quiz row + privacy-floor creator info for the detail
	// payload. The study guide is NOT joined back -- the caller already
	// knows the study_guide_id (it's in the URL on POST and on the
	// quiz row itself). Excludes soft-deleted quizzes (deleted_at IS
	// NULL), soft-deleted creators (u.deleted_at IS NULL), and
	// soft-deleted parent guides (sg.deleted_at IS NULL) so a hydration
	// that races with a parent-cascade soft-delete reports 'not found'
	// rather than rendering an orphaned quiz.
	GetQuizDetail(ctx context.Context, id pgtype.UUID) (GetQuizDetailRow, error)
	// Locked SELECT used by UpdateQuiz (ASK-153). Like
	// GetQuizByIDForUpdate but also joins to the parent study guide
	// so the service can enforce the "parent guide must be live"
	// gate (AC6) inside the same transaction without a second round
	// trip. Locks ONLY the quiz row (FOR UPDATE OF q) -- the parent
	// guide is read-only at this site and we don't want to hold a
	// write lock on it for the duration of the quiz update.
	//
	// Filters NOTHING -- the service inspects the four fields to
	// choose 404 (missing quiz / deleted quiz / deleted guide) vs
	// 403 (not creator) vs proceed.
	GetQuizForUpdateWithParentStatus(ctx context.Context, id pgtype.UUID) (GetQuizForUpdateWithParentStatusRow, error)
	// Hydrates a single question row by id. Used by AddQuizQuestion
	// (ASK-115) to project the freshly-inserted row onto the
	// QuizQuestionResponse wire shape after the tx commits. Mirrors
	// the field selection of ListQuizQuestionsByQuiz so the same Go
	// mapper (mapQuestion) can consume both row types.
	GetQuizQuestionByID(ctx context.Context, id pgtype.UUID) (GetQuizQuestionByIDRow, error)
	// Lookup pair for UpsertResource above. Returns the resources row
	// the viewer owns for this URL; always succeeds because the upsert
	// runs immediately before this in the same tx (either the INSERT
	// wrote the row or it was already there).
	GetResourceByCreatorURL(ctx context.Context, arg GetResourceByCreatorURLParams) (GetResourceByCreatorURLRow, error)
	GetSchool(ctx context.Context, id pgtype.UUID) (School, error)
	// Reads a session row by id. Used by GetPracticeSession (ASK-152)
	// to render the session detail. Unlike LockSessionForCompletion
	// this does NOT FOR UPDATE -- it's a pure read so concurrent
	// writers (SubmitAnswer, CompleteSession) shouldn't block.
	//
	// Returns ALL session fields so the service can build the wire
	// response (including the nullable completed_at the score
	// calculator gates on).
	//
	// No parent quiz / study_guide deletion check: sessions are
	// historical data and remain accessible even after the parent
	// quiz or guide is soft-deleted (ASK-152 spec AC6 + technical
	// note: "sessions must remain accessible even after the quiz is
	// removed").
	GetSessionByID(ctx context.Context, id pgtype.UUID) (PracticeSession, error)
	// Locks the session row and returns ownership + completion state
	// for the answer-submit endpoint (ASK-137). FOR UPDATE serializes
	// against a concurrent SessionComplete (ASK-140 future) so the
	// answer either commits before the completion (recorded) or
	// after (rejected with 409). Filters NOTHING -- the service
	// inspects user_id + completed_at to choose 404 / 403 / 409 /
	// proceed.
	GetSessionForAnswerSubmission(ctx context.Context, id pgtype.UUID) (GetSessionForAnswerSubmissionRow, error)
	// Locked SELECT used at the start of DeleteStudyGuide. SELECT FOR
	// UPDATE prevents concurrent deletes from racing on the same guide
	// (one wins with 204, the other sees the row already-deleted in its
	// transaction's snapshot and returns 404). Filters NOTHING -- the
	// service inspects deleted_at + creator_id to choose 404 vs 403 vs
	// proceed.
	GetStudyGuideByIDForUpdate(ctx context.Context, id pgtype.UUID) (GetStudyGuideByIDForUpdateRow, error)
	// The detail endpoint's main query (ASK-114). Returns the guide's own
	// columns + a compact course payload + a compact creator payload
	// + two inline aggregates as subqueries:
	//   * vote_score    -- SUM(up/down votes)
	//   * is_recommended -- EXISTS in study_guide_recommendations
	//
	// The viewer's own vote (user_vote) ships in a separate query
	// (GetUserVoteForGuide) because sqlc does not infer nullable output
	// columns from LEFT JOIN / subquery expressions on enum-typed columns
	// -- it reads the schema's NOT NULL constraint and types the output
	// non-nullable. An extra round trip is cheaper than fighting sqlc's
	// type inference; the PRD's "batching as separate queries" guidance
	// explicitly allows it.
	//
	// Soft-delete invariants:
	//   * sg.deleted_at IS NULL  -- excludes deleted guides (→ 404)
	//   * u.deleted_at IS NULL   -- creator must be live (ASK-143 convention)
	//
	// Privacy floor: no email, no clerk_id. Creator exposes only
	// id/first_name/last_name.
	GetStudyGuideDetail(ctx context.Context, id pgtype.UUID) (GetStudyGuideDetailRow, error)
	GetUserIDByClerkID(ctx context.Context, clerkID string) (pgtype.UUID, error)
	// Returns the viewer's own vote on the guide, or sql.ErrNoRows when
	// the viewer has not voted. The service maps ErrNoRows to a nil
	// user_vote in the response (JSON null, not omitted).
	GetUserVoteForGuide(ctx context.Context, arg GetUserVoteForGuideParams) (VoteDirection, error)
	// Live-presence probe used by both vote endpoints. Returns TRUE only
	// when the guide row exists AND is not soft-deleted. The vote service
	// gates on this before the upsert/delete so a missing-or-deleted
	// guide returns 404 with a clear message rather than e.g. trampling
	// through to the SQL layer and surfacing a generic FK error.
	GuideExistsAndLive(ctx context.Context, id pgtype.UUID) (bool, error)
	// Quizzes write + read queries (ASK-150 / ASK-136).
	//
	// The create flow is wrapped in a single InTx in the service layer:
	// InsertQuiz -> N x InsertQuizQuestion -> M x InsertQuizAnswerOption.
	// A failure at any step rolls everything back, so a partial quiz can
	// never be observed by another reader.
	//
	// The post-insert hydration runs OUTSIDE the transaction (commit
	// happens first) using GetQuizDetail + ListQuizQuestionsByQuiz +
	// ListQuizAnswerOptionsByQuiz. The two-list fan-out matches the
	// studyguides detail pattern -- mapping options back onto questions
	// happens in Go because pgx returns flat rowsets and the question
	// count is small (<=100 per quiz).
	//
	// Privacy floor on the creator payload mirrors studyguides: id +
	// first_name + last_name only. No email, no clerk_id.
	// Live-presence probe for the create-quiz endpoint. Returns TRUE
	// only when the guide row exists AND is not soft-deleted. The
	// studyguides package has an identical query (GuideExistsAndLive);
	// duplicated here so the quizzes service can stay decoupled from
	// the studyguides Repository interface (sqlc generates queriers
	// per package -- both call the same row but live in different
	// generated method tables).
	GuideExistsAndLiveForQuizzes(ctx context.Context, id pgtype.UUID) (bool, error)
	// Lookup for DetachFile (ASK-124). Returns TRUE when the (file,
	// guide) join row exists. Used as the 404 short-circuit before the
	// delete fires -- we want a clean 'File attachment not found' rather
	// than relying on DeleteGuideFile :execrows which can't distinguish
	// 'never existed' from 'concurrent detach happened first'.
	GuideFileAttached(ctx context.Context, arg GuideFileAttachedParams) (bool, error)
	// Bumps practice_sessions.correct_answers by 1. Called only when
	// the inserted answer was correct (ASK-137 AC8). Wrapped in the
	// same tx as InsertPracticeAnswer so a failure rolls back the
	// answer row too -- the counter and the underlying answer can
	// never disagree.
	IncrementSessionCorrectAnswers(ctx context.Context, id pgtype.UUID) error
	InsertFile(ctx context.Context, arg InsertFileParams) (File, error)
	// Creates the (file_id, study_guide_id) join row. Uses ON CONFLICT
	// DO NOTHING + RETURNING so a duplicate attach surfaces as
	// sql.ErrNoRows in Go, which the service maps to a 409 'File is
	// already attached to this study guide'. Same pattern as
	// recommendations + JoinSection.
	//
	// No attached_by column on this join table (unlike
	// study_guide_resources) -- file ownership is determined from
	// files.user_id instead, and the dual-authz check on detach
	// compares against guide.creator_id + file.user_id.
	InsertGuideFile(ctx context.Context, arg InsertGuideFileParams) (pgtype.Timestamptz, error)
	// Creates the (resource_id, study_guide_id, attached_by) join row.
	// The PK is (resource_id, study_guide_id) so a same-resource-and-guide
	// duplicate raises a unique_violation -- but the user-facing 409
	// conflict on a duplicate URL is detected EARLIER by
	// URLAlreadyAttachedToGuide (which catches across resource rows
	// with the same URL but different creators). This INSERT's PK
	// failure mode is the narrow concurrency-race: two attachers slip
	// through the pre-check between query 1 and query 4.
	InsertGuideResource(ctx context.Context, arg InsertGuideResourceParams) error
	// Records the user's answer with the backend-determined
	// is_correct + verified flags (ASK-137). The unique constraint
	// uq_practice_answers_session_question on (session_id,
	// question_id) catches duplicate submissions; the service
	// detects the unique-violation pgconn error and surfaces a
	// typed 400 with details {"question_id": "already answered"}.
	//
	// Returns the persisted columns so the handler can render the
	// PracticeAnswerResponse without a re-fetch.
	InsertPracticeAnswer(ctx context.Context, arg InsertPracticeAnswerParams) (InsertPracticeAnswerRow, error)
	// Race-safe insert backed by the partial unique index from migration
	// 20260419083647. ON CONFLICT DO NOTHING means a concurrent start by
	// the same user on the same quiz collapses to "no row inserted"
	// (sqlc returns sql.ErrNoRows for the :one annotation), and the
	// service catches that and falls back to FindIncompleteSession.
	//
	// total_questions is intentionally NOT supplied here -- the column
	// defaults to 0 and is set to the authoritative snapshot row count
	// by SnapshotQuizQuestionsAndUpdateCount in the same tx. This
	// avoids the race window that existed when total_questions was
	// pre-computed via CountQuizQuestions and could disagree with the
	// actual snapshot row count under concurrent quiz edits at
	// READ COMMITTED isolation (gemini + copilot PR #153 feedback).
	//
	// The losing request never touches the quiz_questions snapshot --
	// the winner already created it.
	InsertPracticeSessionIfAbsent(ctx context.Context, arg InsertPracticeSessionIfAbsentParams) (InsertPracticeSessionIfAbsentRow, error)
	// Insert a new quiz row. Returns the columns the service needs to
	// build the QuizDetailResponse without an extra round trip on the
	// write side -- the read-side hydration still happens via
	// GetQuizDetail because the creator's first_name + last_name come
	// from a join to users (and would inflate this RETURNING clause).
	InsertQuiz(ctx context.Context, arg InsertQuizParams) (InsertQuizRow, error)
	// Insert one option row. The service has already validated that
	// exactly one option per MCQ has is_correct=true; for true-false
	// questions the service synthesises two options (`True` + `False`)
	// with the matching is_correct flag.
	InsertQuizAnswerOption(ctx context.Context, arg InsertQuizAnswerOptionParams) error
	// Insert a single question row. reference_answer is only meaningful
	// for `freeform` questions; the service passes NULL for the other
	// two types. sort_order is required (the service sets a stable
	// value -- either the user-supplied integer or the array index).
	InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) (pgtype.UUID, error)
	// Study guide list queries (ASK-104).
	//
	// Every ListStudyGuides* variant uses the same CTE structure so the
	// per-row aggregates (vote_score, is_recommended, quiz_count) are
	// computed once and can be referenced from the outer WHERE clause
	// (e.g. for the score-sorted cursor predicate). The CTE pattern also
	// keeps the 8 named variants near-identical apart from ORDER BY + the
	// cursor predicate, which makes future maintenance (e.g. adding a new
	// sort field) a mechanical edit.
	//
	// Soft-delete invariants enforced everywhere:
	//   * sg.deleted_at IS NULL       — excludes guides marked for deletion
	//   * u.deleted_at IS NULL        — excludes guides authored by a
	//                                   soft-deleted user; matches the
	//                                   convention established by ASK-143's
	//                                   section roster (a soft-deleted user
	//                                   disappears from public surfaces)
	//   * quizzes.deleted_at IS NULL  — quiz_count excludes deleted quizzes
	//
	// Privacy floor on the creator payload: only id + first_name + last_name
	// are selected. No email, no clerk_id -- same rule as
	// SectionMemberResponse in ASK-143.
	// Insert a new guide and return all the columns the service needs to
	// construct the StudyGuideDetail response without an extra round trip.
	// The course preflight (in service.go) gates on AssertCourseExists so
	// the FK violation is unreachable in normal flow; the FK still acts
	// as a backstop if a course is hard-deleted between preflight + insert.
	InsertStudyGuide(ctx context.Context, arg InsertStudyGuideParams) (InsertStudyGuideRow, error)
	// Inserts the (study_guide_id, recommended_by) row and returns the
	// created_at PLUS the recommender's privacy-floor identity
	// (first_name + last_name) via a CTE join to users. One round trip
	// builds the entire RecommendationResponse payload; without the
	// CTE the service would need a second SELECT against users just to
	// pull the recommender's name.
	//
	// The (study_guide_id, recommended_by) PK from the schema makes a
	// duplicate insert raise unique_violation (Postgres SQLSTATE 23505),
	// which the service catches and maps to apperrors.ErrConflict (409).
	InsertStudyGuideRecommendation(ctx context.Context, arg InsertStudyGuideRecommendationParams) (InsertStudyGuideRecommendationRow, error)
	// Adds the user to the section as a 'student'. ON CONFLICT DO NOTHING
	// keeps duplicate joins atomic (no PK violation surfacing) and concurrency
	// safe; the service layer treats an empty result as the 409 "Already a
	// member of this section" case.
	JoinSection(ctx context.Context, arg JoinSectionParams) (CourseMember, error)
	// Hard-deletes the membership row. RETURNING lets the service detect a
	// no-op delete (sql.ErrNoRows) and map it to the 404 "Not a member of
	// this section" response.
	LeaveSection(ctx context.Context, arg LeaveSectionParams) (pgtype.UUID, error)
	// Returns sections with a live member_count via LEFT JOIN (so sections
	// with zero members still appear). Ordered most-recent term first using
	// start_date when present, falling back to section_code. NULLS LAST keeps
	// sections without a known start_date at the bottom.
	ListCourseSections(ctx context.Context, courseID pgtype.UUID) ([]ListCourseSectionsRow, error)
	ListCoursesCreatedAtAsc(ctx context.Context, arg ListCoursesCreatedAtAscParams) ([]ListCoursesCreatedAtAscRow, error)
	ListCoursesCreatedAtDesc(ctx context.Context, arg ListCoursesCreatedAtDescParams) ([]ListCoursesCreatedAtDescRow, error)
	// All ListCourses* variants share the same WHERE template
	// (school_id, department, q filters + sort-specific cursor) and only
	// differ in ORDER BY direction and the cursor field shape. This mirrors
	// the per-sort-variant pattern in files.sql -- sqlc cannot parameterize
	// ORDER BY, so each direction gets its own named query.
	//
	// The default sort (by department) uses a composite (department, number, id)
	// cursor because (department) alone is not unique; the other sort fields
	// use a simpler (field, id) cursor since the field is paired with the
	// primary key as a tiebreaker.
	ListCoursesDepartmentAsc(ctx context.Context, arg ListCoursesDepartmentAscParams) ([]ListCoursesDepartmentAscRow, error)
	ListCoursesDepartmentDesc(ctx context.Context, arg ListCoursesDepartmentDescParams) ([]ListCoursesDepartmentDescRow, error)
	ListCoursesNumberAsc(ctx context.Context, arg ListCoursesNumberAscParams) ([]ListCoursesNumberAscRow, error)
	ListCoursesNumberDesc(ctx context.Context, arg ListCoursesNumberDescParams) ([]ListCoursesNumberDescRow, error)
	ListCoursesTitleAsc(ctx context.Context, arg ListCoursesTitleAscParams) ([]ListCoursesTitleAscRow, error)
	ListCoursesTitleDesc(ctx context.Context, arg ListCoursesTitleDescParams) ([]ListCoursesTitleDescRow, error)
	// Attached files for the guide detail payload. Privacy floor: no
	// user_id, no s3_key, no checksum. The file list shows only what a
	// viewer needs to see: what's attached, what type, and how big.
	//
	// Filters f.status = 'complete' so files mid-upload (pending) or
	// failed don't surface in the guide detail -- a frontend that tried
	// to download such a file would get a broken link. Only successfully
	// uploaded files are visible to non-owners; the upload author's own
	// file list (via the files endpoints) shows all statuses so they can
	// retry or remove.
	ListGuideFiles(ctx context.Context, studyGuideID pgtype.UUID) ([]ListGuideFilesRow, error)
	// Non-deleted quizzes for the guide + question_count per quiz. The
	// LEFT JOIN ensures quizzes with zero questions still appear with
	// question_count = 0.
	ListGuideQuizzesWithQuestionCount(ctx context.Context, studyGuideID pgtype.UUID) ([]ListGuideQuizzesWithQuestionCountRow, error)
	// Recommenders list for the guide detail payload. Same privacy floor
	// as CreatorSummary -- id + first_name + last_name only. Excludes
	// recommenders whose user record is soft-deleted.
	ListGuideRecommenders(ctx context.Context, studyGuideID pgtype.UUID) ([]ListGuideRecommendersRow, error)
	// Attached resources for the guide detail payload. No creator info
	// in the SELECT list -- the caller doesn't need to know who attached
	// the resource.
	ListGuideResources(ctx context.Context, studyGuideID pgtype.UUID) ([]ListGuideResourcesRow, error)
	// Returns every section a user is enrolled in with the compact
	// course + school payload the dashboard renders. Optional term + role
	// filters use sqlc.narg so the WHERE branch short-circuits when
	// they're absent. Sort is fixed: most-recent term first (lexicographic
	// "Spring 2026" > "Fall 2025" is acceptable for MVP per the spec),
	// then department + number for stable in-term ordering.
	ListMyEnrollments(ctx context.Context, arg ListMyEnrollmentsParams) ([]ListMyEnrollmentsRow, error)
	ListOwnedFilesCreatedAsc(ctx context.Context, arg ListOwnedFilesCreatedAscParams) ([]ListOwnedFilesCreatedAscRow, error)
	ListOwnedFilesCreatedDesc(ctx context.Context, arg ListOwnedFilesCreatedDescParams) ([]ListOwnedFilesCreatedDescRow, error)
	ListOwnedFilesMimeAsc(ctx context.Context, arg ListOwnedFilesMimeAscParams) ([]ListOwnedFilesMimeAscRow, error)
	ListOwnedFilesMimeDesc(ctx context.Context, arg ListOwnedFilesMimeDescParams) ([]ListOwnedFilesMimeDescRow, error)
	ListOwnedFilesNameAsc(ctx context.Context, arg ListOwnedFilesNameAscParams) ([]ListOwnedFilesNameAscRow, error)
	ListOwnedFilesNameDesc(ctx context.Context, arg ListOwnedFilesNameDescParams) ([]ListOwnedFilesNameDescRow, error)
	ListOwnedFilesSizeAsc(ctx context.Context, arg ListOwnedFilesSizeAscParams) ([]ListOwnedFilesSizeAscRow, error)
	ListOwnedFilesSizeDesc(ctx context.Context, arg ListOwnedFilesSizeDescParams) ([]ListOwnedFilesSizeDescRow, error)
	ListOwnedFilesStatusAsc(ctx context.Context, arg ListOwnedFilesStatusAscParams) ([]ListOwnedFilesStatusAscRow, error)
	ListOwnedFilesStatusDesc(ctx context.Context, arg ListOwnedFilesStatusDescParams) ([]ListOwnedFilesStatusDescRow, error)
	ListOwnedFilesUpdatedAsc(ctx context.Context, arg ListOwnedFilesUpdatedAscParams) ([]ListOwnedFilesUpdatedAscRow, error)
	ListOwnedFilesUpdatedDesc(ctx context.Context, arg ListOwnedFilesUpdatedDescParams) ([]ListOwnedFilesUpdatedDescRow, error)
	// All answer options for one question, ordered by sort_order then
	// id. Used by AddQuizQuestion (ASK-115) to attach the freshly-
	// inserted option rows to the question on the response. The
	// single-question scope keeps the read narrow -- no need to load
	// every option on the parent quiz when the caller only wants the
	// new question.
	ListQuizAnswerOptionsByQuestion(ctx context.Context, questionID pgtype.UUID) ([]QuizAnswerOption, error)
	// All answer options for every question in a quiz, ordered by
	// question_id then sort_order then id. The mapper groups by
	// question_id in Go to attach options to their parent question.
	// The triple-key ordering keeps the option list deterministic.
	ListQuizAnswerOptionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]QuizAnswerOption, error)
	// All questions for a quiz, ordered by sort_order then id (the id
	// tiebreaker keeps the response deterministic when two questions
	// happen to share a sort_order -- the spec doesn't enforce
	// uniqueness on sort_order). Returns reference_answer so the
	// mapper can emit it as `correct_answer` on freeform questions.
	ListQuizQuestionsByQuiz(ctx context.Context, quizID pgtype.UUID) ([]ListQuizQuestionsByQuizRow, error)
	// Lists every non-soft-deleted quiz attached to a study guide
	// (ASK-136). Each row carries the privacy-floor creator payload
	// (id + first_name + last_name only -- mirrors the studyguides
	// surface) plus a server-computed question_count via LEFT JOIN +
	// COUNT, so a quiz with zero questions still surfaces with a 0
	// count rather than being silently dropped by an INNER JOIN.
	//
	// Soft-delete invariants:
	//   * q.deleted_at IS NULL  -- excludes soft-deleted quizzes
	//                              (AC3: studyguide with mixed live +
	//                              deleted quizzes only returns the live
	//                              ones)
	//   * u.deleted_at IS NULL  -- excludes quizzes whose creator's user
	//                              record was soft-deleted (matches the
	//                              ASK-143 convention used by
	//                              GetStudyGuideDetail)
	//
	// The parent study guide's deleted_at is checked separately by the
	// service via GuideExistsAndLiveForQuizzes BEFORE this query runs --
	// a missing or soft-deleted guide returns 404 even when this query
	// would have returned an empty array. Keeps the 404 vs 200-empty
	// distinction crisp.
	//
	// Order: created_at DESC with id DESC as the deterministic
	// tiebreaker (the spec calls for "newest first"). The id tiebreaker
	// prevents a flaky test on a Postgres that happens to insert two
	// rows in the same microsecond.
	ListQuizzesByStudyGuide(ctx context.Context, studyGuideID pgtype.UUID) ([]ListQuizzesByStudyGuideRow, error)
	ListSchools(ctx context.Context, arg ListSchoolsParams) ([]School, error)
	// Returns the section roster joined against users for first/last name.
	// Privacy floor: SELECT lists ONLY the five fields exposed in the
	// SectionMemberResponse schema (user_id, first_name, last_name, role,
	// joined_at). DO NOT add email, clerk_id, or any other user column to
	// this list -- the endpoint is reachable by any authenticated user.
	//
	// Soft-deleted users (users.deleted_at IS NOT NULL) are excluded -- the
	// codebase's soft-delete convention is enforced by the partial indexes
	// idx_users_deleted_at and idx_users_active_email. A user's soft-delete
	// is the signal that they want to disappear from the product, so they
	// must not surface in a public-by-design roster. The cursor still
	// advances past them in the (joined_at, user_id) keyset, so removing
	// them mid-iteration just shrinks the page rather than skipping live
	// members.
	//
	// Optional role filter via sqlc.narg short-circuits when absent. Keyset
	// pagination on (joined_at, user_id) -- joined_at alone isn't unique
	// (multiple users can join in the same second on a busy section), so
	// user_id is the tiebreaker that keeps the keyset a strict total order.
	ListSectionMembers(ctx context.Context, arg ListSectionMembersParams) ([]ListSectionMembersRow, error)
	// All answers submitted in a session, ordered by answered_at ASC so
	// the response renders them in the order the user produced them.
	// Used by the resume path to populate the `answers` array in
	// PracticeSessionResponse. Returns an empty slice (not nil) for
	// freshly-created sessions where no answers exist yet -- the
	// mapper renders that as `[]` rather than `null` per spec.
	ListSessionAnswers(ctx context.Context, sessionID pgtype.UUID) ([]ListSessionAnswersRow, error)
	ListStudyGuidesNewestAsc(ctx context.Context, arg ListStudyGuidesNewestAscParams) ([]ListStudyGuidesNewestAscRow, error)
	ListStudyGuidesNewestDesc(ctx context.Context, arg ListStudyGuidesNewestDescParams) ([]ListStudyGuidesNewestDescRow, error)
	ListStudyGuidesScoreAsc(ctx context.Context, arg ListStudyGuidesScoreAscParams) ([]ListStudyGuidesScoreAscRow, error)
	// Default sort. Multi-column keyset on (vote_score, view_count,
	// updated_at, id) -- each column after vote_score is a tiebreaker for
	// the previous one; id is the final strict-total-order tiebreaker.
	ListStudyGuidesScoreDesc(ctx context.Context, arg ListStudyGuidesScoreDescParams) ([]ListStudyGuidesScoreDescRow, error)
	ListStudyGuidesUpdatedAsc(ctx context.Context, arg ListStudyGuidesUpdatedAscParams) ([]ListStudyGuidesUpdatedAscRow, error)
	ListStudyGuidesUpdatedDesc(ctx context.Context, arg ListStudyGuidesUpdatedDescParams) ([]ListStudyGuidesUpdatedDescRow, error)
	ListStudyGuidesViewsAsc(ctx context.Context, arg ListStudyGuidesViewsAscParams) ([]ListStudyGuidesViewsAscRow, error)
	ListStudyGuidesViewsDesc(ctx context.Context, arg ListStudyGuidesViewsDescParams) ([]ListStudyGuidesViewsDescRow, error)
	// Cursor-paginated keyset list of the authenticated user's
	// practice sessions for one quiz (ASK-149). Sorted by
	// (started_at DESC, id DESC) so newest attempts appear first;
	// id is the deterministic tie-breaker on the (vanishingly rare)
	// case of two sessions sharing started_at to the microsecond.
	//
	// Filters:
	//   * Scoped to (user_id, quiz_id). The handler/service
	//     anchors user_id on the JWT so users cannot list each
	//     other's sessions even if they spoof the path param.
	//   * status_filter optional:
	//       NULL       -- both active + completed (interleaved by started_at)
	//       'active'   -- completed_at IS NULL  (in-progress only)
	//       'completed'-- completed_at IS NOT NULL (finalised only)
	//   * Keyset cursor (cursor_started_at + cursor_id) is the
	//     started_at + id of the LAST row from the previous page.
	//     Both nullable args MUST be set together; the service
	//     decodes them as a pair from the opaque base64 cursor and
	//     never sends one without the other. The query enforces
	//     the pair invariant defensively in SQL (see the WHERE
	//     clause below) so a half-set cursor surfaces as a clear
	//     error rather than a mysteriously empty page (Postgres
	//     tuple comparison against NULL evaluates to NULL, which
	//     filters every row out). copilot PR #158 feedback.
	//
	// Pagination: the service passes page_limit = caller_limit + 1
	// so it can detect has_more without an extra COUNT query --
	// if more than caller_limit rows come back, the extra row is
	// trimmed and has_more=true.
	//
	// No parent quiz / study_guide deletion check inline here: the
	// service gates the call with CheckQuizLiveForSession before
	// invoking this query. A deleted parent surfaces as 404 before
	// this list query runs, so a stale "list" call against a
	// soft-deleted quiz cannot leak rows. (CheckQuizLiveForSession
	// is itself a DB query -- the "no DB hit" path is from the
	// application logic perspective, not the literal HTTP layer.)
	ListUserSessionsForQuiz(ctx context.Context, arg ListUserSessionsForQuizParams) ([]ListUserSessionsForQuizRow, error)
	// Locks the session row and returns ALL fields the
	// CompleteSession endpoint (ASK-140) needs to assemble its
	// response. FOR UPDATE serializes against a concurrent
	// SubmitAnswer (ASK-137 also FOR UPDATEs the session row), so
	// the spec's "answer-vs-complete race -> first commit wins"
	// semantics fall out naturally:
	//   * answer wins -> complete sees correct_answers updated
	//   * complete wins -> answer's locked SELECT sees completed_at
	//     set and returns 409
	//
	// Returns sql.ErrNoRows when the session doesn't exist; the
	// service maps that to 404. The presence of completed_at on the
	// returned row drives the 409-vs-proceed decision.
	LockSessionForCompletion(ctx context.Context, id pgtype.UUID) (PracticeSession, error)
	// Called by the cleanup job handler once S3 deletion is confirmed.
	MarkFileDeleted(ctx context.Context, fileID pgtype.UUID) error
	// Sets completed_at = now() and returns the timestamp the row
	// now carries. The service uses the returned timestamp to
	// assemble the response without a re-fetch (the rest of the
	// session fields were captured by LockSessionForCompletion in
	// the same tx, so they don't need to round-trip again).
	//
	// This is a blind UPDATE: the service has already verified
	// ownership + completed_at IS NULL inside the same tx via
	// LockSessionForCompletion + the FOR UPDATE row lock. By the
	// time this runs, the only legitimate outcome is "row updated".
	MarkSessionCompleted(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error)
	// Deletes a file grant matching the exact composite key. No-op if the grant
	// does not exist (idempotent).
	RevokeFileGrant(ctx context.Context, arg RevokeFileGrantParams) error
	// Verifies the section exists AND belongs to the supplied course. A
	// section UUID that targets a different course is treated as not found
	// to avoid leaking the existence of unrelated sections via the URL path.
	SectionInCourseExists(ctx context.Context, arg SectionInCourseExistsParams) (bool, error)
	// Records the QStash message ID after publishing the async cleanup job.
	SetFileDeletionJobID(ctx context.Context, arg SetFileDeletionJobIDParams) error
	// Atomic snapshot + total_questions fix-up. Inserts one
	// practice_session_questions row per current quiz_questions row in
	// a single CTE, then updates the session's total_questions to the
	// count of rows actually inserted. Returns the new total_questions
	// so the caller can sync its in-memory session state.
	//
	// The single-statement CTE eliminates the race that existed in the
	// prior two-step approach (CountQuizQuestions sets total_questions
	// on insert, then a separate SnapshotQuizQuestions writes the
	// snapshot). Under Postgres' default READ COMMITTED isolation each
	// statement gets its own snapshot, so a concurrent quiz edit
	// between count and snapshot could leave the two out of sync.
	// Within a single CTE statement, both reads share the same
	// statement-level snapshot, so the count and the snapshot are
	// guaranteed identical (gemini + copilot PR #153 feedback).
	//
	// Subsequent edits to the quiz do not retroactively affect this
	// snapshot:
	//   * New questions added AFTER this statement are not in the snapshot.
	//   * Deleted questions trigger ON DELETE SET NULL on
	//     practice_session_questions.question_id -- the snapshot row
	//     persists with question_id = NULL so total_questions stays
	//     stable.
	SnapshotQuizQuestionsAndUpdateCount(ctx context.Context, arg SnapshotQuizQuestionsAndUpdateCountParams) (int32, error)
	// Marks a file as pending deletion. Only applies if the file is owned by the caller
	// and has not already entered a deletion state (idempotency-safe).
	SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (int64, error)
	// Set deleted_at = now() on the quiz. The service has already
	// verified the row exists, isn't already deleted, and the viewer
	// is the creator -- so this is a blind UPDATE. No cascade: practice
	// sessions, questions, and answer options are preserved per the
	// ASK-102 spec ("preserve historical practice data; the quiz
	// simply becomes invisible to list/detail endpoints").
	SoftDeleteQuiz(ctx context.Context, id pgtype.UUID) error
	// Application-level cascade: soft-delete every non-deleted quiz on
	// the guide. WHERE deleted_at IS NULL preserves the deleted_at
	// timestamp on quizzes that were already soft-deleted before the
	// guide was -- the spec explicitly requires that an already-deleted
	// quiz's deleted_at is NOT updated by this cascade.
	SoftDeleteQuizzesForGuide(ctx context.Context, studyGuideID pgtype.UUID) error
	// Set deleted_at = now() on the guide. The service has already
	// verified the row exists, isn't already deleted, and the viewer is
	// the creator -- so this is a blind UPDATE. The DeleteStudyGuide
	// transaction wraps this + SoftDeleteQuizzesForGuide.
	SoftDeleteStudyGuide(ctx context.Context, id pgtype.UUID) error
	SoftDeleteUserByClerkID(ctx context.Context, clerkID string) (int64, error)
	// Bumps quizzes.updated_at = now() without touching any other
	// column. Called by AddQuizQuestion (ASK-115) so the quiz row's
	// modified-time reflects the structural change. Kept as a focused
	// single-column UPDATE rather than reusing the broader UpdateQuiz
	// query so a future AddQuizQuestion review can spot the intent at
	// a glance and so a CASE expression with both args nil isn't
	// relied on as the "no-op write that bumps updated_at" path.
	TouchQuizUpdatedAt(ctx context.Context, id pgtype.UUID) error
	// Pre-flight conflict check for AttachResource (ASK-111). Returns
	// TRUE when ANY resource with this URL is already attached to the
	// given guide -- regardless of who created the resource row. Lets
	// the service short-circuit to 409 BEFORE the resource upsert, so a
	// duplicate attempt doesn't create or touch a resources row only to
	// discard it on the join PK violation.
	//
	// Why "regardless of creator": the join PK is (resource_id,
	// study_guide_id), so two distinct resource rows (different creators
	// but same URL) could both attach to the same guide without raising
	// the join PK constraint. The spec treats that as a duplicate URL
	// on the guide -- this query enforces the no-duplicate-URLs-per-guide
	// contract at the application layer.
	URLAlreadyAttachedToGuide(ctx context.Context, arg URLAlreadyAttachedToGuideParams) (bool, error)
	// Renames a file. Only applies if owned by the caller and not in a deletion state.
	// Returns sql.ErrNoRows when file is not found, not owned, or in deletion.
	UpdateFile(ctx context.Context, arg UpdateFileParams) (UpdateFileRow, error)
	UpdateFileStatus(ctx context.Context, arg UpdateFileStatusParams) error
	// Partial update for ASK-153. The title column uses the standard
	// COALESCE(narg, current) pattern -- nil means "leave alone".
	//
	// Description uses a CASE expression because COALESCE can't
	// distinguish "field absent in the request" from "field
	// explicitly null in the request" (both encode as SQL NULL once
	// they reach the query layer). The handler resolves the
	// tri-state, sets `clear_description` true on an explicit
	// `description: null` body, and the service drives both args
	// accordingly:
	//   * clear_description=false                 -> column unchanged
	//   * clear_description=true, description=NULL -> column cleared
	//   * clear_description=true, description="x"  -> column set to "x"
	//
	// The service is responsible for 404 / 403 gating before this
	// query runs (via GetQuizForUpdateWithParentStatus). updated_at
	// is bumped to now() on every successful call -- the at-least-
	// one-field rule is enforced in Go so this query is never
	// reached for an empty PATCH.
	UpdateQuiz(ctx context.Context, arg UpdateQuizParams) error
	// Partial update for ASK-129. Each updatable column uses COALESCE(narg,
	// current) so a nil arg from Go means "leave this column alone" and a
	// non-nil arg means "replace with the supplied value". The service is
	// responsible for:
	//   * 404 / 403 gating (via GetStudyGuideByIDForUpdate before this).
	//   * Validating the at-least-one-field rule (an empty body is a 400
	//     before this query runs).
	//   * Tag normalization (trim + lowercase + dedupe) -- the array
	//     written here is the final canonical form.
	//
	// The service runs the locked SELECT + this UPDATE in a single
	// transaction so a concurrent delete can't slip in between. updated_at
	// is bumped to now() on every successful call (the UPDATE sees at
	// least the updated_at change even when every other narg is NULL,
	// which matches the spec's "updated_at reflects the latest" guarantee
	// but also means a no-op PATCH still bumps updated_at -- the service's
	// empty-body 400 check prevents that case from reaching SQL).
	UpdateStudyGuide(ctx context.Context, arg UpdateStudyGuideParams) error
	UpsertClerkUser(ctx context.Context, arg UpsertClerkUserParams) (User, error)
	// Inserts a new file grant, returning the row. If the grant already exists
	// (same file_id, grantee_type, grantee_id, permission), updates granted_by
	// and returns the row. Using DO UPDATE SET avoids a race window where
	// concurrent inserts could cause both INSERT and fallback SELECT to miss.
	UpsertFileGrant(ctx context.Context, arg UpsertFileGrantParams) (FileGrant, error)
	// Inserts a new resources row for the (creator_id, url) pair. The
	// ON CONFLICT DO NOTHING preserves the existing row's title /
	// description / type when the viewer has used this URL before -- a
	// silent overwrite would mutate state visible to the resource's
	// other attachments (the same row may be attached to other guides
	// + courses).
	//
	// Paired with GetResourceByCreatorURL: the service runs both calls
	// in sequence, then uses the SELECT'd row regardless of whether the
	// INSERT actually wrote.
	UpsertResource(ctx context.Context, arg UpsertResourceParams) error
	// Cast or change a vote (ASK-139). Inserts a new (user_id,
	// study_guide_id, vote) row when the viewer has not voted, or
	// updates the existing row's vote when the direction changes. Same-
	// direction re-submits hit the WHERE clause on the DO UPDATE branch
	// and become a true no-op (no row touched, no trigger fired,
	// updated_at preserved). The (user_id, study_guide_id) PK from the
	// schema is what makes ON CONFLICT resolve correctly.
	UpsertStudyGuideVote(ctx context.Context, arg UpsertStudyGuideVoteParams) error
	// Combined live-presence + role-gate probe for the recommend
	// endpoints (ASK-147 + ASK-101). Returns one row when the viewer
	// holds instructor or ta role in AT LEAST ONE section of the guide's
	// course AND the guide is live (not soft-deleted).
	//
	// Returns three booleans so the service can distinguish 404 from
	// 403 with a single round trip:
	//   * guide_exists  -- guide row present AND deleted_at IS NULL
	//   * has_role      -- viewer is instructor/ta in some section
	//                      of the guide's course (ignored if guide
	//                      doesn't exist)
	//
	// Combining the two checks into a single query (rather than two
	// sequential calls) keeps the recommend hot path at one DB round
	// trip for the gate; the actual insert/delete is the second.
	//
	// NULL-semantics note: when the guide doesn't exist, the inner
	// `guide` CTE returns 0 rows, so `(SELECT course_id FROM guide)` is
	// NULL, and `cs.course_id = NULL` is always FALSE (not NULL-equal).
	// That makes `has_role` correctly false for missing guides without
	// needing a separate WHERE EXISTS guard. The service short-circuits
	// on !guide_exists before inspecting has_role, so the two booleans
	// are independent by contract even though they correlate in this
	// edge case.
	ViewerCanRecommendForGuide(ctx context.Context, arg ViewerCanRecommendForGuideParams) (ViewerCanRecommendForGuideRow, error)
}

var _ Querier = (*Queries)(nil)
