// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_guides.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseExistsForGuides = `-- name: CourseExistsForGuides :one

SELECT EXISTS (
  SELECT 1 FROM courses WHERE id = $1::uuid
) AS exists
`

// Study guide list queries (ASK-104).
//
// Every ListStudyGuides* variant uses the same CTE structure so the
// per-row aggregates (vote_score, is_recommended, quiz_count) are
// computed once and can be referenced from the outer WHERE clause
// (e.g. for the score-sorted cursor predicate). The CTE pattern also
// keeps the 8 named variants near-identical apart from ORDER BY + the
// cursor predicate, which makes future maintenance (e.g. adding a new
// sort field) a mechanical edit.
//
// Soft-delete invariants enforced everywhere:
//   - sg.deleted_at IS NULL       — excludes guides marked for deletion
//   - u.deleted_at IS NULL        — excludes guides authored by a
//     soft-deleted user; matches the
//     convention established by ASK-143's
//     section roster (a soft-deleted user
//     disappears from public surfaces)
//   - quizzes.deleted_at IS NULL  — quiz_count excludes deleted quizzes
//
// Privacy floor on the creator payload: only id + first_name + last_name
// are selected. No email, no clerk_id -- same rule as
// SectionMemberResponse in ASK-143.
// Single-row probe used by the list handler to disambiguate "course
// missing" (404) from "course exists but has no guides" (200 empty
// array). Separate from courses.CourseExists only because sqlc-generated
// queriers are per-file; the predicate is identical.
func (q *Queries) CourseExistsForGuides(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, courseExistsForGuides, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listStudyGuidesNewestAsc = `-- name: ListStudyGuidesNewestAsc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $4::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $5::text IS NULL
      OR sg.title ILIKE '%' || $5::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $5::text || '%' ESCAPE '\'
      )
    )
    AND ($6::text[] IS NULL OR sg.tags @> $6::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::timestamptz IS NULL
  OR (created_at, id) > (
    $1::timestamptz,
    $2::uuid
  )
)
ORDER BY created_at ASC, id ASC
LIMIT $3
`

type ListStudyGuidesNewestAscParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesNewestAscRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesNewestAsc(ctx context.Context, arg ListStudyGuidesNewestAscParams) ([]ListStudyGuidesNewestAscRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesNewestAsc,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesNewestAscRow
	for rows.Next() {
		var i ListStudyGuidesNewestAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesNewestDesc = `-- name: ListStudyGuidesNewestDesc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $4::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $5::text IS NULL
      OR sg.title ILIKE '%' || $5::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $5::text || '%' ESCAPE '\'
      )
    )
    AND ($6::text[] IS NULL OR sg.tags @> $6::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::timestamptz IS NULL
  OR (created_at, id) < (
    $1::timestamptz,
    $2::uuid
  )
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListStudyGuidesNewestDescParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesNewestDescRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesNewestDesc(ctx context.Context, arg ListStudyGuidesNewestDescParams) ([]ListStudyGuidesNewestDescRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesNewestDesc,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesNewestDescRow
	for rows.Next() {
		var i ListStudyGuidesNewestDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesScoreAsc = `-- name: ListStudyGuidesScoreAsc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $6::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $7::text IS NULL
      OR sg.title ILIKE '%' || $7::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $7::text || '%' ESCAPE '\'
      )
    )
    AND ($8::text[] IS NULL OR sg.tags @> $8::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::bigint IS NULL
  OR (vote_score, view_count, updated_at, id) > (
    $1::bigint,
    $2::bigint,
    $3::timestamptz,
    $4::uuid
  )
)
ORDER BY vote_score ASC, view_count ASC, updated_at ASC, id ASC
LIMIT $5
`

type ListStudyGuidesScoreAscParams struct {
	CursorVoteScore pgtype.Int8        `json:"cursor_vote_score"`
	CursorViewCount pgtype.Int8        `json:"cursor_view_count"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesScoreAscRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesScoreAsc(ctx context.Context, arg ListStudyGuidesScoreAscParams) ([]ListStudyGuidesScoreAscRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesScoreAsc,
		arg.CursorVoteScore,
		arg.CursorViewCount,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesScoreAscRow
	for rows.Next() {
		var i ListStudyGuidesScoreAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesScoreDesc = `-- name: ListStudyGuidesScoreDesc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*)
      FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $6::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $7::text IS NULL
      OR sg.title ILIKE '%' || $7::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $7::text || '%' ESCAPE '\'
      )
    )
    AND ($8::text[] IS NULL OR sg.tags @> $8::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::bigint IS NULL
  OR (vote_score, view_count, updated_at, id) < (
    $1::bigint,
    $2::bigint,
    $3::timestamptz,
    $4::uuid
  )
)
ORDER BY vote_score DESC, view_count DESC, updated_at DESC, id DESC
LIMIT $5
`

type ListStudyGuidesScoreDescParams struct {
	CursorVoteScore pgtype.Int8        `json:"cursor_vote_score"`
	CursorViewCount pgtype.Int8        `json:"cursor_view_count"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesScoreDescRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

// Default sort. Multi-column keyset on (vote_score, view_count,
// updated_at, id) -- each column after vote_score is a tiebreaker for
// the previous one; id is the final strict-total-order tiebreaker.
func (q *Queries) ListStudyGuidesScoreDesc(ctx context.Context, arg ListStudyGuidesScoreDescParams) ([]ListStudyGuidesScoreDescRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesScoreDesc,
		arg.CursorVoteScore,
		arg.CursorViewCount,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesScoreDescRow
	for rows.Next() {
		var i ListStudyGuidesScoreDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesUpdatedAsc = `-- name: ListStudyGuidesUpdatedAsc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $4::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $5::text IS NULL
      OR sg.title ILIKE '%' || $5::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $5::text || '%' ESCAPE '\'
      )
    )
    AND ($6::text[] IS NULL OR sg.tags @> $6::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::timestamptz IS NULL
  OR (updated_at, id) > (
    $1::timestamptz,
    $2::uuid
  )
)
ORDER BY updated_at ASC, id ASC
LIMIT $3
`

type ListStudyGuidesUpdatedAscParams struct {
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesUpdatedAscRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesUpdatedAsc(ctx context.Context, arg ListStudyGuidesUpdatedAscParams) ([]ListStudyGuidesUpdatedAscRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesUpdatedAsc,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesUpdatedAscRow
	for rows.Next() {
		var i ListStudyGuidesUpdatedAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesUpdatedDesc = `-- name: ListStudyGuidesUpdatedDesc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $4::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $5::text IS NULL
      OR sg.title ILIKE '%' || $5::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $5::text || '%' ESCAPE '\'
      )
    )
    AND ($6::text[] IS NULL OR sg.tags @> $6::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::timestamptz IS NULL
  OR (updated_at, id) < (
    $1::timestamptz,
    $2::uuid
  )
)
ORDER BY updated_at DESC, id DESC
LIMIT $3
`

type ListStudyGuidesUpdatedDescParams struct {
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesUpdatedDescRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesUpdatedDesc(ctx context.Context, arg ListStudyGuidesUpdatedDescParams) ([]ListStudyGuidesUpdatedDescRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesUpdatedDesc,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesUpdatedDescRow
	for rows.Next() {
		var i ListStudyGuidesUpdatedDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesViewsAsc = `-- name: ListStudyGuidesViewsAsc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $5::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $6::text IS NULL
      OR sg.title ILIKE '%' || $6::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $6::text || '%' ESCAPE '\'
      )
    )
    AND ($7::text[] IS NULL OR sg.tags @> $7::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::bigint IS NULL
  OR (view_count, updated_at, id) > (
    $1::bigint,
    $2::timestamptz,
    $3::uuid
  )
)
ORDER BY view_count ASC, updated_at ASC, id ASC
LIMIT $4
`

type ListStudyGuidesViewsAscParams struct {
	CursorViewCount pgtype.Int8        `json:"cursor_view_count"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesViewsAscRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesViewsAsc(ctx context.Context, arg ListStudyGuidesViewsAscParams) ([]ListStudyGuidesViewsAscRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesViewsAsc,
		arg.CursorViewCount,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesViewsAscRow
	for rows.Next() {
		var i ListStudyGuidesViewsAscRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudyGuidesViewsDesc = `-- name: ListStudyGuidesViewsDesc :many
WITH scored AS (
  SELECT
    sg.id, sg.title, sg.description, sg.tags, sg.course_id,
    sg.view_count, sg.created_at, sg.updated_at,
    u.id AS creator_id, u.first_name AS creator_first_name, u.last_name AS creator_last_name,
    COALESCE((
      SELECT SUM(CASE WHEN vote = 'up' THEN 1 ELSE -1 END)::bigint
      FROM study_guide_votes
      WHERE study_guide_id = sg.id
    ), 0)::bigint AS vote_score,
    EXISTS (
      SELECT 1 FROM study_guide_recommendations
      WHERE study_guide_id = sg.id
    ) AS is_recommended,
    (
      SELECT COUNT(*) FROM quizzes
      WHERE study_guide_id = sg.id AND deleted_at IS NULL
    )::bigint AS quiz_count
  FROM study_guides sg
  JOIN users u ON u.id = sg.creator_id
  WHERE sg.course_id = $5::uuid
    AND sg.deleted_at IS NULL
    AND u.deleted_at IS NULL
    AND (
      $6::text IS NULL
      OR sg.title ILIKE '%' || $6::text || '%' ESCAPE '\'
      OR EXISTS (
        SELECT 1 FROM unnest(sg.tags) AS t
        WHERE t ILIKE '%' || $6::text || '%' ESCAPE '\'
      )
    )
    AND ($7::text[] IS NULL OR sg.tags @> $7::text[])
)
SELECT id, title, description, tags, course_id, view_count,
       created_at, updated_at,
       creator_id, creator_first_name, creator_last_name,
       vote_score, is_recommended, quiz_count
FROM scored
WHERE (
  $1::bigint IS NULL
  OR (view_count, updated_at, id) < (
    $1::bigint,
    $2::timestamptz,
    $3::uuid
  )
)
ORDER BY view_count DESC, updated_at DESC, id DESC
LIMIT $4
`

type ListStudyGuidesViewsDescParams struct {
	CursorViewCount pgtype.Int8        `json:"cursor_view_count"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
	CourseID        pgtype.UUID        `json:"course_id"`
	Q               pgtype.Text        `json:"q"`
	Tags            []string           `json:"tags"`
}

type ListStudyGuidesViewsDescRow struct {
	ID               pgtype.UUID        `json:"id"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Tags             []string           `json:"tags"`
	CourseID         pgtype.UUID        `json:"course_id"`
	ViewCount        int32              `json:"view_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatorID        pgtype.UUID        `json:"creator_id"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	VoteScore        int64              `json:"vote_score"`
	IsRecommended    bool               `json:"is_recommended"`
	QuizCount        int64              `json:"quiz_count"`
}

func (q *Queries) ListStudyGuidesViewsDesc(ctx context.Context, arg ListStudyGuidesViewsDescParams) ([]ListStudyGuidesViewsDescRow, error) {
	rows, err := q.db.Query(ctx, listStudyGuidesViewsDesc,
		arg.CursorViewCount,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
		arg.CourseID,
		arg.Q,
		arg.Tags,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudyGuidesViewsDescRow
	for rows.Next() {
		var i ListStudyGuidesViewsDescRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CourseID,
			&i.ViewCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorID,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.VoteScore,
			&i.IsRecommended,
			&i.QuizCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
