// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: study_guide_file_chunks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const deleteChunksByFile = `-- name: DeleteChunksByFile :exec
DELETE FROM study_guide_file_chunks
WHERE file_id = $1
`

// Manual chunk delete. Cascade from `files` already removes them on
// file delete; this is for the worker's "re-chunk this file" path
// where we want to wipe the previous chunking before re-inserting.
func (q *Queries) DeleteChunksByFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChunksByFile, fileID)
	return err
}

const getChunksByFile = `-- name: GetChunksByFile :many
SELECT id, file_id, chunk_idx, text, embedding, page, heading, tokens, created_at
FROM study_guide_file_chunks
WHERE file_id = $1
ORDER BY chunk_idx ASC
`

// All chunks for a file in chunk order. Used by the file-detail
// diagnostic view + by the worker's count-reconciliation step.
func (q *Queries) GetChunksByFile(ctx context.Context, fileID pgtype.UUID) ([]StudyGuideFileChunk, error) {
	rows, err := q.db.Query(ctx, getChunksByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudyGuideFileChunk
	for rows.Next() {
		var i StudyGuideFileChunk
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.ChunkIdx,
			&i.Text,
			&i.Embedding,
			&i.Page,
			&i.Heading,
			&i.Tokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertStudyGuideFileChunk = `-- name: InsertStudyGuideFileChunk :one

INSERT INTO study_guide_file_chunks (
  file_id,
  chunk_idx,
  text,
  embedding,
  page,
  heading,
  tokens
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (file_id, chunk_idx) DO UPDATE SET
  text       = EXCLUDED.text,
  embedding  = EXCLUDED.embedding,
  page       = EXCLUDED.page,
  heading    = EXCLUDED.heading,
  tokens     = EXCLUDED.tokens
RETURNING id, file_id, chunk_idx, text, embedding, page, heading, tokens, created_at
`

type InsertStudyGuideFileChunkParams struct {
	FileID    pgtype.UUID     `json:"file_id"`
	ChunkIdx  int32           `json:"chunk_idx"`
	Text      string          `json:"text"`
	Embedding pgvector.Vector `json:"embedding"`
	Page      pgtype.Int4     `json:"page"`
	Heading   pgtype.Text     `json:"heading"`
	Tokens    int32           `json:"tokens"`
}

// Queries for the chunk + embedding store (ASK-219).
//
// Two consumer surfaces (separate tickets ship them):
//
//   - ASK-221 chunk+embed worker writes rows after extracting +
//     chunking a file. Idempotent via UPSERT on (file_id, chunk_idx)
//     so re-runs are safe.
//   - ASK-223 grounded generation reads top-k chunks via
//     SearchChunksByEmbedding, filtered to the files the user
//     attached to the active study guide.
//
// This ticket (ASK-219) only ships the schema + queries; the workers
// and retrieval endpoint land in separate PRs.
// Single-row insert with UPSERT semantics: re-running the embed
// worker on the same (file_id, chunk_idx) overwrites the row,
// which keeps the worker idempotent across retries.
func (q *Queries) InsertStudyGuideFileChunk(ctx context.Context, arg InsertStudyGuideFileChunkParams) (StudyGuideFileChunk, error) {
	row := q.db.QueryRow(ctx, insertStudyGuideFileChunk,
		arg.FileID,
		arg.ChunkIdx,
		arg.Text,
		arg.Embedding,
		arg.Page,
		arg.Heading,
		arg.Tokens,
	)
	var i StudyGuideFileChunk
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.ChunkIdx,
		&i.Text,
		&i.Embedding,
		&i.Page,
		&i.Heading,
		&i.Tokens,
		&i.CreatedAt,
	)
	return i, err
}

const searchChunksByEmbedding = `-- name: SearchChunksByEmbedding :many
SELECT
  c.id,
  c.file_id,
  c.chunk_idx,
  c.text,
  c.embedding,
  c.page,
  c.heading,
  c.tokens,
  c.created_at,
  (c.embedding <=> $1)::float8 AS distance
FROM study_guide_file_chunks c
WHERE c.file_id = ANY($2::uuid[])
ORDER BY c.embedding <=> $1
LIMIT $3::int
`

type SearchChunksByEmbeddingParams struct {
	Embedding pgvector.Vector `json:"embedding"`
	FileIds   []pgtype.UUID   `json:"file_ids"`
	K         int32           `json:"k"`
}

type SearchChunksByEmbeddingRow struct {
	ID        pgtype.UUID        `json:"id"`
	FileID    pgtype.UUID        `json:"file_id"`
	ChunkIdx  int32              `json:"chunk_idx"`
	Text      string             `json:"text"`
	Embedding pgvector.Vector    `json:"embedding"`
	Page      pgtype.Int4        `json:"page"`
	Heading   pgtype.Text        `json:"heading"`
	Tokens    int32              `json:"tokens"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Distance  float64            `json:"distance"`
}

// Top-k cosine similarity search over a fixed set of files. The
// caller (ASK-223 grounded generation) passes the list of file ids
// the user attached to a study guide so retrieval is naturally
// scoped to that user's content.
//
// Returns chunks ordered by ascending cosine *distance*, i.e. most
// similar first. The HNSW index uses `vector_cosine_ops` so this
// ORDER BY clause is index-backed.
//
// The `<=>` operator is pgvector's cosine-distance operator. We
// expose distance back to the caller (`distance` column) so the
// ranker can filter on a similarity threshold without a second
// query.
func (q *Queries) SearchChunksByEmbedding(ctx context.Context, arg SearchChunksByEmbeddingParams) ([]SearchChunksByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchChunksByEmbedding, arg.Embedding, arg.FileIds, arg.K)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChunksByEmbeddingRow
	for rows.Next() {
		var i SearchChunksByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.ChunkIdx,
			&i.Text,
			&i.Embedding,
			&i.Page,
			&i.Heading,
			&i.Tokens,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
